### ISSUE TITLE
进入地址显示Gateway Timeout || Enter the address to display Gateway Timeout when accessing

### ISSUE THREAD

**Issue by MagicQiyi** [msgbyte/tailchat#101]
我的服务器配置:2核4G
系统:Alibaba Cloud 3

一切步骤都按照官网文档安装，就是在访问的时候出现Gateway Timeout

---
My server configuration: 2 cores 4G
System: Alibaba Cloud 3

All steps are installed according to the official website documentation, that is, Gateway Timeout

**Comment by moonrailgun** [comment]
检查你的防火墙，是否开启了对应端口。
同时检查你的容器是否所有的容器运行成功
