### ISSUE TITLE
FILE_LIMIT文件参数不生效 || FILE_LIMIT file parameter doesn't take effect

### ISSUE THREAD

**Issue by ZZZ-zero** [msgbyte/tailchat#107]
我在docker-compose.env中添加了`FILE_LIMIT=314572800`
如图
![image](https://github.com/msgbyte/tailchat/assets/30883525/5f6b933a-d0ff-4694-be2b-e255ddbc327d)
同时管理页面也显示生效
![image](https://github.com/msgbyte/tailchat/assets/30883525/7c6752ba-fea5-417c-a77a-dcaf4e4c88d8)
但是上传文件或图片时仍然限制1MB
![image](https://github.com/msgbyte/tailchat/assets/30883525/0faecc01-8539-4867-979d-63ba58deafbc)
我尝试删除所有容器重新构建，仍然不起作用

---
I added `FILE_LIMIT=314572800` in docker-compose.env
as shown in the picture
![image](https://github.com/msgbyte/tailchat/assets/30883525/5f6b933a-d0ff-4694-be2b-e255ddbc327d)
At the same time, the management page is also displayed in effect
![image](https://github.com/msgbyte/tailchat/assets/30883525/7c6752ba-fea5-417c-a77a-dcaf4e4c88d8)
But there is still a limit of 1MB when uploading files or images
![image](https://github.com/msgbyte/tailchat/assets/30883525/0faecc01-8539-4867-979d-63ba58deafbc)
I tried to delete all containers and rebuild, still doesn't work

**Comment by moonrailgun** [comment]
文档里说了部分改动需要清理缓存才能正常使用。

你可以选择如下方式:
- 手动进入redis清理缓存
- 在admin的缓存管理清理所有缓存
- 把redis容器删了重启启动(不是重启)

你可以访问后台的`/api/config/client` 查看发送到前端的全局配置，uploadFileLimit就是你的上传文件上限
