### ISSUE TITLE
Service 'plugin:com.msgbyte.agora.generateJoinInfo' is not found.

### ISSUE THREAD

**Issue by cnkids** [msgbyte/tailchat#108]
开启语音视频会议弹出提示Service 'plugin:com.msgbyte.agora.generateJoinInfo' is not found.该怎么解决？

**Comment by moonrailgun** [comment]
你需要在后端进行一些配置才能正常启用

具体见文档: https://tailchat.msgbyte.com/zh-Hans/docs/meeting/agora
