### ISSUE TITLE
在tailchat-client-sdk没有监听消息功能 || There is no function of listening to messages in tailchat-client-sdk

### ISSUE THREAD

**Issue by GhostThirteen** [msgbyte/tailchat#115]
希望大佬能在SDK中新增监听群组消息功能看😉😉😉

---
I hope you can add the function of listening to group messages in the SDK 😉😉😉

**Comment by moonrailgun** [comment]
更新 `tailchat-client-sdk` 版本到 1.0.6 即可

相关文档: https://tailchat.msgbyte.com/zh-Hans/docs/advanced-usage/openapp/ws
