### ISSUE TITLE
管理员账号 || administrator account

### ISSUE THREAD

**Issue by 781087595** [msgbyte/tailchat#116]
请问有没有管理用户账号密码的管理员账号，或者docker部署在服务器的，如何在服务器查看特定用户设置的密码，或者帮助重置密码

---
May I ask if there is an administrator account for managing user account passwords, or if docker is deployed on the server, how to view the password set by a specific user on the server, or help reset the password

**Comment by Thexiaoyuqaq** [comment]
有管理员后台的 详见
https://tailchat.msgbyte.com/zh-Hans/docs/deployment/admin

目前还没有管理员这种东西
