### ISSUE TITLE
希望添加后台权限组功能和内置新的语音插件 || Hope to add background permission group function and built-in new voice plug-in

### ISSUE THREAD

**Issue by Thexiaoyuqaq** [msgbyte/tailchat#117]
1.后台权限组:
  现在的后台登入需要使用的是配置文件的账号密码,可以添加一个后台的权限组分 普通成员和管理员 管理员账户可以输入自己的账密登入后台
2.内置一个新的语音插件(仅仅建议)
 最开始我是用的RocketChat 但是感觉太复杂了,发现了tailchat就很不错,但那边的语音功能(一个需安装的应用 名字是Jitsi Meet) 这个语音功能我感觉很不错 可以共享屏幕 也可以开白板等的 希望可以尝试接入?
3.开放平台功能
    事情经过:
    这个的对接在文档只看见了nodejs的方法,希望可以补充一下文档,我尝试使用python的方法:使用flask开放一个接口,通过 开放平台中中的机器人设置消息回调地址为flask的地址,当机器人被at的时候会有一串消息json通过post方式发送到消息回调这个地址,可以获取post请求的内容,来制作接收部分(这样可以给一些人做点参考)  然后发送部分我发现就需要在整一个请求还需要做个登入,感觉有点复杂
   提个小建议:
    开放平台.机器人这里的消息回调地址下面可以加个websocket(因为这个可以支持收和发)的方式

---
1. Background permission group:
  The current background login needs to use the account password of the configuration file, and a background permission component can be added. Ordinary members and administrators. Administrator accounts can enter their own account passwords to log in to the background.
2. Built-in a new voice plug-in (suggestion only)
 At first I used RocketChat, but it felt too complicated. I found tailchat, which is very good, but the voice function over there (an application that needs to be installed, the name is Jitsi Meet) I think this voice function is very good. It can share the screen, open the whiteboard, etc. Hope you can try to access it?
3. Open platform functions
    What happened:
    I only saw the nodejs method in the documentation for this connection. I hope I can add to the documentation. I tried to use the python method: use flask to open an interface, and set the message callback address to the address of flask through the robot in the open platform. When the robot is at, there will be a series of messages.
   Make a small suggestion:
    Open platform. A websocket can be added under the message callback address of the robot (because this can support receiving and sending)

**Comment by moonrailgun** [comment]
1. 这个没有计划去做更加细分的权限控制。欢迎pr
2. 正在重做，并支持私有化部署。顺利的话下下个版本就能看到
3. websocket 开放平台sdk正在开发中，进度见 #115。另外其他语言的文档应该是有的: https://tailchat.msgbyte.com/zh-Hans/docs/advanced-usage/openapp/bot

**Comment by Thexiaoyuqaq** [comment]
> 1. 这个没有计划去做更加细分的权限控制。欢迎pr
> 2. 正在重做，并支持私有化部署。顺利的话下下个版本就能看到
> 3. websocket 开放平台sdk正在开发中，进度见 [在tailchat-client-sdk没有监听消息功能 || There is no function of listening to messages in tailchat-client-sdk #115](https://github.com/msgbyte/tailchat/issues/115)。另外其他语言的文档应该是有的: https://tailchat.msgbyte.com/zh-Hans/docs/advanced-usage/openapp/bot
> 
> 1. There is no plan to do more subdivided permission control. Welcome to PR
> 2. It is being redone and supports privatized deployment. If it goes well, you can see it in the next version
> 3. The websocket open platform sdk is under development, see [在tailchat-client-sdk没有监听消息功能 || There is no function of listening to messages in tailchat-client-sdk #115](https://github.com/msgbyte/tailchat/issues/115) for progress. In addition, there should be documents in other languages: https://tailchat.msgbyte.com/zh-Hans/docs/advanced-usage/openapp/bot

好的好的
