### ISSUE TITLE
声网的插件安装后，分享屏幕是否可以添加全屏功能 || After the plug-in of the sound network is installed, can the shared screen be added to the full screen function?

### ISSUE THREAD

**Issue by Shiradan** [msgbyte/tailchat#121]
声网插件安装了没问题，但是分享屏幕的时候无法全屏对方分享的屏幕，也可能是我眼瞎，找遍了页面都没找到全屏按钮，这个能做一下优化吗，感谢！

---
There is no problem with the installation of the Shengwang plug-in, but when sharing the screen, the screen shared by the other party cannot be fully screened. It may also be that I am blind. I have searched the page and found no full-screen button. Can this be optimized, thank you!

**Comment by moonrailgun** [comment]
新版本的livekit解决方案已经添加全屏功能。可以移步新的解决方案尝试
