### ISSUE TITLE
com.msgbyte.meeting 怎么用啊？ || com.msgbyte.meeting?

### ISSUE THREAD

**Issue by kkqy** [msgbyte/tailchat#123]
安装了插件，但是打开页面以后提示
```
插件加载失败:
- com.msgbyte.meeting
```
我看文档里关于 部署视频会议的内容，貌似是部署的一个独立的应用
https://tailchat.msgbyte.com/zh-Hans/docs/meeting/deployment
我按照文档部署以后，是通过swag单独提供的一个网页服务，输入房间号和昵称就能加入房间，
但是这个不是应该和tailchat整合的么？

另一个页面：
https://tailchat.msgbyte.com/zh-Hans/docs/meeting/plugin
显示的TODO，是因为目前这个插件尚未完成么？

---
The plug-in is installed, but it prompts after opening the page
```
Plugin failed to load:
- com.msgbyte.meeting
```
I read the content about deploying video conferencing in the document, it seems to be an independent application deployed
https://tailchat.msgbyte.com/zh-Hans/docs/meeting/deployment
After I deploy according to the document, it is a web service provided separately through swag. Enter the room number and nickname to join the room.
But shouldn't this be integrated with tailchat?

Another page:
https://tailchat.msgbyte.com/zh-Hans/docs/meeting/plugin
Is the TODO displayed because the plugin is not yet complete?

How to use

**Comment by moonrailgun** [comment]
是的，目前该插件处于不可用的状态。下个版本我会上线新版本的视频会议解决方案，另外如果你比较着急的话可以使用agora方案，这是比较成熟且无需部署的解决方案

https://tailchat.msgbyte.com/zh-Hans/docs/meeting/agora
