### ISSUE TITLE
开发插件中遇到的一些困难和问题 || Some difficulties and problems encountered in the development of plug-ins

### ISSUE THREAD

**Issue by kkqy** [msgbyte/tailchat#129]
我目前在尝试基于[livekit](https://livekit.io/)做一个支持好友间私聊的音视频通话插件，

目前思路如下，
1. regPluginPanelAction貌似只能用于群聊，所以我用regChatInputAction注册了一个音视频通话按钮，用户点击以后，由服务端生成roomid和key，然后同时将这个roomid和key作为自定义的card消息的参数通过sendMsg发送给对方。
2. 对方收到roomid和key以后，渲染一个card，上面包含“同意”和“拒绝”按钮。
3. 如果点击拒绝，则流程结束。
4. 如果点击同意，则通过roomid和key请求后端申请token，并通过该token进入room，同时服务端生成另一个token并通知发起者，发起者进入room，完成语音通话。
5. 通话结束断开，然后聊天记录里生成通话时间和时长的消息。

这个思路遇到的问题是：
* 第四步，被邀请方点击 同意 以后，服务端没办法通知发起方获取token并进入room，因为sendMsg只在regChatInputAction的回调里可以用，服务端貌似也没有能直接通知客户端的接口，或许有，而我没找到？当然有个退一步的办法，就是发起方发起语音邀请以后，不管对方同意与否，都先进room等着，但是这样做会消耗额外的服务端资源（因为livekit是自建webrtc的中继）。
* 第五步，语音通话完成以后，我还需要更新这个card，类似微信那种显示通话时间和时长，也就是说这个card还得展现通话的状态。目前没有修改历史消息的API，服务端也没有办法通知客户端刷新历史消息。退一步，不更新历史消息，我想新增一条消息，用于记录通话完成时间都没办法，因为sendMsg只在regChatInputAction的回调里可以用。

理想状态是：发起语音以后，弹出一个新窗口，类似微信语音通话那种，然后对方那边也弹出一个窗口，提示有人邀请语音，接受或者拒绝都在窗口里进行，然后通话完成以后，生成一个聊天记录用于记录语音通话的时间和时长。

在消息记录里显示并不是必须的，但是目前我只找到了通过actions.sendMsg给好友传递信息的方法，没有找到那种隐式传递信息的方法，甚至连获取对方userid的方法都没找到，getJWTUserInfo只能获取到自己的ID。

原本想参考com.msgbyte.agora，但是发现实现原理完全不同，com.msgbyte.agora貌似是根据group_id和panel_id生成群组的唯一roomid。然后群成员各自加入，也就是说需要手动告诉其他人加入，而没有类似微信那样的”邀请“提醒的过程。
另外，regPluginPanelAction 的onClick至少能获取到group_id和panel_id，regChatInputAction的onClick里却获取不到会话的任何信息，只有三个方法用于修改、发送 消息，这部分是否有待改进？

---
I am currently trying to make an audio and video call plug-in that supports private chats between friends based on [livekit](https://livekit.io/),

The current thinking is as follows,
1. It seems that regPluginPanelAction can only be used for group chat, so I use regChatInputAction to register an audio and video call button. After the user clicks, the server will generate a roomid and key, and then use the roomid and key as the parameters of the custom card message Send it to the other party through sendMsg.
2. After receiving the roomid and key, the other party renders a card with "Agree" and "Deny" buttons on it.
3. If you click Decline, the process ends.
4. If you click Agree, request the backend to apply for a token through the roomid and key, and use the token to enter the room. At the same time, the server generates another token and notifies the initiator. The initiator enters the room and completes the voice call.
5. When the call ends, the call is disconnected, and a message of the call time and duration is generated in the chat record.

The problem with this idea is:
* The fourth step, after the invited party clicks to agree, the server has no way to notify the initiator to obtain the token and enter the room, because sendMsg can only be used in the callback of regChatInputAction, and the server does not seem to have an interface that can directly notify the client, maybe there is , and I don't find it? Of course, there is a way to take a step back, that is, after the initiator initiates a voice invitation, no matter whether the other party agrees or not, they will wait in the advanced room, but doing so will consume additional server resources (because livekit is a relay of self-built webrtc).
* Step 5. After the voice call is completed, I need to update the card, similar to WeChat to display the call time and duration, that is to say, the card has to show the status of the call. Currently there is no API for modifying historical messages, and the server has no way to notify the client to refresh historical messages. Taking a step back and not updating the historical messages, I want to add a new message to record the call completion time, because sendMsg can only be used in the callback of regChatInputAction.

The ideal state is: after the voice is initiated, a new window pops up, similar to the WeChat voice call, and then a window pops up on the other side, prompting someone to invite the voice, accept or reject in the window, and then after the call is completed, generate a Chat logs are used to record the time and duration of voice calls.

It is not necessary to display in the message record, but so far I have only found a method to pass information to friends through actions.sendMsg, and I have not found a method to implicitly pass information, and I have not even found a method to obtain the userid of the other party. getJWTUserInfo You can only get your own ID.

I originally wanted to refer to com.msgbyte.agora, but found that the implementation principle is completely different. Com.msgbyte.agora seems to be the only roomid generated by group_id and panel_id. Then the group members join individually, that is to say, they need to manually tell others to join, and there is no "invitation" reminder process like WeChat.
In addition, the onClick of regPluginPanelAction can at least get the group_id and panel_id, but the onClick of regChatInputAction can't get any information about the session. There are only three methods for modifying and sending messages. Is this part to be improved?

**Comment by moonrailgun** [comment]
首先感谢你对Tailchat的关注与优化。

你可以基于 `com.msgbyte.livekit` 插件做进一步的迭代

> 第四步，被邀请方点击 同意 以后，服务端没办法通知发起方获取token并进入room，因为sendMsg只在regChatInputAction的回调里可以用，服务端貌似也没有能直接通知客户端的接口，或许有，而我没找到？当然有个退一步的办法，就是发起方发起语音邀请以后，不管对方同意与否，都先进room等着，但是这样做会消耗额外的服务端资源（因为livekit是自建webrtc的中继）。

你可以通过在前端插件注册一个自定义socket事件监听。比如通过 `useGlobalSocketEvent` 监听socket事件来获取来自服务端的通知

*以下是来自真实代码的示例*:
客户端监听: 
```tsx
useGlobalSocketEvent(
    'plugin:com.msgbyte.livekit.participantJoined',
    (payload: any) => {
      if (
        payload.groupId === props.groupId &&
        payload.panelId === props.panelId &&
        payload.participant
      ) {
        setDisplayParticipants((state) => [...state, payload.participant]);
      }
    }
  );
```

在服务端通过以下命令进行通知
```ts
this.roomcastNotify(ctx, groupId, 'participantJoined', {
  groupId,
  panelId,
  participant: payload.participant,
});
```

> 第五步，语音通话完成以后，我还需要更新这个card，类似微信那种显示通话时间和时长，也就是说这个card还得展现通话的状态。目前没有修改历史消息的API，服务端也没有办法通知客户端刷新历史消息。退一步，不更新历史消息，我想新增一条消息，用于记录通话完成时间都没办法，因为sendMsg只在regChatInputAction的回调里可以用。

更新消息内容目前在计划内，如果你急的话可以开个issue关于更新用户可以编辑消息内容的issue，语音通话完成的回调应该通过webhook来接受通知，你可以直接复用`com.msgbyte.livekit`插件的 `webhook-receiver` 来接受来自`livekit`的推送

> 另外，regPluginPanelAction 的onClick至少能获取到group_id和panel_id，regChatInputAction的onClick里却获取不到会话的任何信息，只有三个方法用于修改、发送 消息，这部分是否有待改进？

你可以使用context来获取更多的上下文信息。如:
```ts
const { groupId, panelId } = useGroupPanelContext();
```

**Comment by kkqy** [comment]
> 首先感谢你对Tailchat的关注与优化。
> 
> 你可以基于 `com.msgbyte.livekit` 插件做进一步的迭代
> 
> > 第四步，被邀请方点击 同意 以后，服务端没办法通知发起方获取token并进入room，因为sendMsg只在regChatInputAction的回调里可以用，服务端貌似也没有能直接通知客户端的接口，或许有，而我没找到？当然有个退一步的办法，就是发起方发起语音邀请以后，不管对方同意与否，都先进room等着，但是这样做会消耗额外的服务端资源（因为livekit是自建webrtc的中继）。
> 
> 你可以通过在前端插件注册一个自定义socket事件监听。比如通过 `useGlobalSocketEvent` 监听socket事件来获取来自服务端的通知
> 
> _以下是来自真实代码的示例_: 客户端监听:
> 
> ```tsx
> useGlobalSocketEvent(
>     'plugin:com.msgbyte.livekit.participantJoined',
>     (payload: any) => {
>       if (
>         payload.groupId === props.groupId &&
>         payload.panelId === props.panelId &&
>         payload.participant
>       ) {
>         setDisplayParticipants((state) => [...state, payload.participant]);
>       }
>     }
>   );
> ```
> 
> 在服务端通过以下命令进行通知
> 
> ```ts
> this.roomcastNotify(ctx, groupId, 'participantJoined', {
>   groupId,
>   panelId,
>   participant: payload.participant,
> });
> ```
> 
> > 第五步，语音通话完成以后，我还需要更新这个card，类似微信那种显示通话时间和时长，也就是说这个card还得展现通话的状态。目前没有修改历史消息的API，服务端也没有办法通知客户端刷新历史消息。退一步，不更新历史消息，我想新增一条消息，用于记录通话完成时间都没办法，因为sendMsg只在regChatInputAction的回调里可以用。
> 
> 更新消息内容目前在计划内，如果你急的话可以开个issue关于更新用户可以编辑消息内容的issue，语音通话完成的回调应该通过webhook来接受通知，你可以直接复用`com.msgbyte.livekit`插件的 `webhook-receiver` 来接受来自`livekit`的推送
> 
> > 另外，regPluginPanelAction 的onClick至少能获取到group_id和panel_id，regChatInputAction的onClick里却获取不到会话的任何信息，只有三个方法用于修改、发送 消息，这部分是否有待改进？
> 
> 你可以使用context来获取更多的上下文信息。如:
> 
> ```ts
> const { groupId, panelId } = useGroupPanelContext();
> ```

好的，这个插件我5天前就开始尝试在做，但我刚刚才看到tailchat最新增加了livekit的插件（有点巧合了，哈哈）
我先关闭这个issue，看看官方的livekit的代码，目前文档不完整，自带插件反而是更好的参考资料。
