### ISSUE TITLE
插件的后端如何删除消息？ || How to delete the message at the backend of the plug-in?

### ISSUE THREAD

**Issue by kkqy** [msgbyte/tailchat#130]
`server\packages\sdk\src\services\base.ts`
文件里没有找到相关的API

---
`server\packages\sdk\src\services\base.ts`
The relevant API is not found in the file

**Comment by moonrailgun** [comment]
`ctx.call('chat.message.deleteMessage', { messageId: 'xxxxxxxxxxxxx' })`

这是一个微服务调用的方式, 你可以在tailchat中看到很多类似的操作
