### ISSUE TITLE
useGlobalSocketEvent 不能在外部使用 || useGlobalSocketEvent cannot be used externally

### ISSUE THREAD

**Issue by kkqy** [msgbyte/tailchat#131]
因为如果直接在外部使用useGlobalSocketEvent ，会提示
`Warning: Invalid hook call. Hooks can only be called inside of the body of a function component.`
所以为了接受事件消息，我必须创建一个组件，然后在组件里使用useGlobalSocketEvent ，然后“想办法”把这个组件挂在页面里。
目前那些注册函数没有一个能持续保持组件的，我试过regCustomPanel，它也只是在点击以后才会渲染组件。
而用openModal又不能隐藏，因为我只是为了能监听事件，并不希望它显示出来。

那么我如何在插件中持续保持监听事件呢？

---
Because if you use useGlobalSocketEvent directly externally, you will be prompted
`Warning: Invalid hook call. Hooks can only be called inside of the body of a function component.`
So in order to receive event messages, I have to create a component, then use useGlobalSocketEvent in the component, and then "find a way" to hang this component in the page.
Currently, none of those registration functions can keep components. I tried regCustomPanel, and it only renders components after clicking.
And it can't be hidden with openModal, because I just want to listen to events and don't want it to be displayed.

So how do I keep listening to events in the plugin?

**Comment by moonrailgun** [comment]
这是因为socket连接本身就是只有在组件挂载的时候才会连接，有部分页面是没有socket的。

关于如何做到长久挂载组件但不显示，你可以参考livekit插件的做法: 

https://github.com/msgbyte/tailchat/blob/50991708f2611e1b207755adc79c08d29a36946a/server/plugins/com.msgbyte.livekit/web/plugins/com.msgbyte.livekit/src/index.tsx#L32-L47

`useIsShow` 是一个用于侧边栏会生效的一个hooks。默认为 `() => true`, 你可以自己实现相关的逻辑来控制显示隐藏。

另外react是支持挂载dom的, 这就涉及到一些react的骚操作了
