### ISSUE TITLE
failed to solve: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount4173707505/Dockerfile: no such file or directory

### ISSUE THREAD

**Issue by cnkids** [msgbyte/tailchat#133]
failed to solve: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount4173707505/Dockerfile: no such file or directory

拉取镜像安装出现如上提示

**Comment by moonrailgun** [comment]
拉取镜像后修改镜像名字了么？

**Comment by cnkids** [comment]
重新操作之后又出现
vendors-6575d636.ff33f74e312467fa21ab.js:91 WebSocket connection to 'wss://test.rclandy.com/socket.io/?EIO=4&transport=websocket' failed:

**Comment by moonrailgun** [comment]
检查一下你的服务的连通性。可以通过 `https://test.rclandy.com/health` 来查看

**Comment by cnkids** [comment]
奥，搞定，是我的nginx配置问题
