### ISSUE TITLE
大佬你好，请问docker-compose中的103行和104行的端口是哪个容器的端口？ || Hello, big brother, which container port is the port in line 103 and line 104 in docker-compose?

### ISSUE THREAD

**Issue by himonster1** [msgbyte/tailchat#134]
https://github.com/msgbyte/tailchat/blob/master/docker-compose.yml

中的`11000`和`11001`端口是哪个服务产生的？是第五行：`service-core`的端口其中之一吗？

或者说这个docker-compose不用这个Traefik行不行呢？不用Traefik的话 用Nginx应该反代哪个服务呢？`service-core`吗？

网上搜了好几篇教程，官方文档也看了，看不懂了 又是Traefik又是Nginx的，Traefik本来就是反代的，为啥还要用Nginx在反代一次呢？

---
https://github.com/msgbyte/tailchat/blob/master/docker-compose.yml

Which service generated the `11000` and `11001` ports in ? Is the fifth line: one of the ports of `service-core`?

Or can this docker-compose work without this Traefik? If Traefik is not used, which service should be replaced by Nginx? `service-core`?

I searched several tutorials on the Internet, and read the official documents, but I can’t understand it. It’s Traefik and Nginx. Traefik is originally a reverse generation, so why use Nginx to reverse generation again?

**Comment by himonster1** [comment]
还有就是

https://github.com/msgbyte/tailchat/blob/master/docker-compose.env

中的第12行API_URL的网址是写到数据库里面的吗？必须要用https开头吗？https开头的话需要提前配置证书吗？如果要配置的话是给谁配置呢？`service-core`服务吗？

能不能写个内网地址，然后直接用nginx反代呢？

**Comment by moonrailgun** [comment]
> 中的11000和11001端口是哪个服务产生的？是第五行：service-core的端口其中之一吗？

是 traefik 

> 或者说这个docker-compose不用这个Traefik行不行呢？不用Traefik的话 用Nginx应该反代哪个服务呢？service-core吗？

可以不用，你可以自己手动写匹配规则，Traefik的目的是把多个服务共用一个端口

> Traefik本来就是反代的，为啥还要用Nginx在反代一次呢？

并不影响吧？nginx不适合微服务场景。你可以不用nginx，直接暴露11000端口

> 第12行API_URL的网址是写到数据库里面的吗

no

> 必须要用https开头吗？https开头的话需要提前配置证书吗？如果要配置的话是给谁配置呢？service-core服务吗？

可以不用https。另外你可以不关心service-core

**Comment by shenjackyuanjie** [comment]
ping: 询问问题可以关了吧

**Comment by moonrailgun** [comment]
Thanks your reminder.
closed
