### ISSUE TITLE
websocket 消息不同步 || websocket message out of sync

### ISSUE THREAD

**Issue by davidheartdev** [msgbyte/tailchat#138]
1、文字频道发送消息不能同步，只能通过刷新
下图为手机发送消息
![fbdd6733489b654871784df419b8e86d](https://github.com/msgbyte/tailchat/assets/66203320/d10a1437-0276-4d65-a143-aeec53d8f1e9)

电脑端没有同步接收到消息，但是开发者模式看，是收到了消息没有更新到页面上。
![image](https://github.com/msgbyte/tailchat/assets/66203320/96fa932c-8f44-4d69-a9ea-b9aaf826c430)

---
1. The message sent by the text channel cannot be synchronized, only by refreshing
The picture below shows the mobile phone sending a message
![fbdd6733489b654871784df419b8e86d](https://github.com/msgbyte/tailchat/assets/66203320/d10a1437-0276-4d65-a143-aeec53d8f1e9)

The computer did not receive the message synchronously, but in the developer mode, the message was received but not updated to the page.
![image](https://github.com/msgbyte/tailchat/assets/66203320/96fa932c-8f44-4d69-a9ea-b9aaf826c430)

**Comment by moonrailgun** [comment]
这是因为之前的一个feature修改了消息同步策略，本人发送的消息只会在发送端出现在屏幕上。

我再想想怎么优化一下

**Comment by davidheartdev** [comment]
最好是本人不同端也能同步。
我把这应用到团队开发工作当中去，相应的工作开相应的房间。
还想要房间加锁功能。
前几年做过国外项目，就是discord来管理不同工作，非常方便。
这个项目已经很接近了，把这个用起来。
有时间我也来贡献代码。

**Comment by chenpotatos** [comment]
const WebSocket = require('ws');

const wss = new WebSocket.Server({ port: 8080 });

wss.on('connection', (ws) => {
  console.log('Client connected');

  ws.on('message', (message) => {
    console.log(`Received message: ${message}`);

    // 向所有连接的客户端广播消息
    wss.clients.forEach((client) => {
      if (client.readyState === WebSocket.OPEN) {
        client.send(message);
      }
    });
  });

  ws.on('close', () => {
    console.log('Client disconnected');
  });
});
```

客户端代码（浏览器）：

```javascript
const ws = new WebSocket('ws://localhost:8080');

ws.onopen = () => {
  console.log('Connected to server');
};

ws.onmessage = (event) => {
  const message = event.data;
  console.log(`Received message: ${message}`);

  // 在此处处理接收到的消息
};

ws.onclose = () => {
  console.log('Disconnected from server');
};

// 发送消息到服务器
ws.send('Hello, server!');

**Comment by chenpotatos** [comment]
`const WebSocket = require('ws');

const wss = new WebSocket.Server({ port: 8080 });

wss.on('connection', (ws) => {
  console.log('Client connected');

  ws.on('message', (message) => {
    console.log(`Received message: ${message}`);

    // 向所有连接的客户端广播消息
    wss.clients.forEach((client) => {
      if (client.readyState === WebSocket.OPEN) {
        client.send(message);
      }
    });
  });

  ws.on('close', () => {
    console.log('Client disconnected');
  });
});
```

客户端代码（浏览器）：

```javascript
const ws = new WebSocket('ws://localhost:8080');

ws.onopen = () => {
  console.log('Connected to server');
};

ws.onmessage = (event) => {
  const message = event.data;
  console.log(`Received message: ${message}`);

  // 在此处处理接收到的消息
};

ws.onclose = () => {
  console.log('Disconnected from server');
};

// 发送消息到服务器
ws.send('Hello, server!');`

**Comment by chenpotatos** [comment]
这样似乎可以实现websocket多端同步

**Comment by moonrailgun** [comment]
在nightly 应该已经解决这个问题了，辛苦看一下
