### ISSUE TITLE
必须加好友才能开启聊天&不支持搜索聊天记录 || must add friends to open chat & does not support searching chat records

### ISSUE THREAD

**Issue by zhiling00** [msgbyte/tailchat#139]
1、目前必须加好友才能开启聊天，而标识符寻找麻烦。是否可以：设置不加好友就直接私信，或者在群组成员界面点击成员直接跳转到添加该成员的页面
2、群组现在不支持搜索聊天记录，是否可支持

---
1. At present, it is necessary to add friends to open the chat, and the identifier is troublesome. Is it possible: set direct private message without adding friends, or click on a member on the group member interface to directly jump to the page for adding the member
2. The group does not support searching chat records now, whether it can support

**Comment by moonrailgun** [comment]
是否介意将问题分开提？因为一个issue往往管理着一个问题。将两个完全不同的问题合并在一起将很难被管理与讨论。

**Comment by moonrailgun** [comment]
duplicate with #140 #141
