### ISSUE TITLE
必须加好友才能开启聊天，是否可以简化操作 || You must add friends to open the chat, can the operation be simplified?

### ISSUE THREAD

**Issue by zhiling00** [msgbyte/tailchat#140]
目前必须加好友才能开启聊天，而标识符寻找麻烦。是否可以：设置不加好友就直接私信，或者在群组成员界面点击成员直接跳转到添加该成员的页面

---
Currently you have to be friends to start a chat, and identifiers are looking for trouble. Is it possible: set direct private message without adding friends, or click on a member on the group member interface to jump directly to the page where the member is added

**Comment by moonrailgun** [comment]
Finished in `v1.8.10`.

Here is release note: [https://tailchat.msgbyte.com/blog/release-1.8.10](https://tailchat.msgbyte.com/blog/release-1.8.10)
