### ISSUE TITLE
进行反代后打开域名出现:可能资源加载出现了一些问题，请手动刷新重试一下 || After reverse generation, open the domain name: There may be some problems with resource loading, please manually refresh and try again

### ISSUE THREAD

**Issue by mcraftbbs** [msgbyte/tailchat#151]
进行反代后打开域名出现:可能资源加载出现了一些问题，请手动刷新重试一下

---
Opening the domain name after reverse generation: There may be some problems with resource loading, please manually refresh and try again

**Comment by moonrailgun** [comment]
先检查一下是否为网络问题，能出现提示说明反向代理的index.html是没有问题的，需要检查是否因为网络问题导致后面的资源加载速度慢。

**Comment by mcraftbbs** [comment]
> 先检查一下是否为网络问题，能出现提示说明反向代理的index.html是没有问题的，需要检查是否因为网络问题导致后面的资源加载速度慢。
> 
> First check whether it is a network problem. A prompt will appear indicating that the index.html of the reverse proxy is correct. You need to check whether the loading speed of subsequent resources is slow due to network problems.

网络是够的。直连ip能进入，但是换到域名就不行。

**Comment by mcraftbbs** [comment]
已解决
