### ISSUE TITLE
要部署后台的话2核2g不够吗？ || If you want to deploy the backend, won’t 2 cores and 2g be enough?

### ISSUE THREAD

**Issue by ZakiuC** [msgbyte/tailchat#154]
我在2核2g的服务器上部署后台后运行会直接占满内存然后卡死，但是不用后台就不会直接拉满占用，是因为配置不够吗？

---
After I deploy the backend on a 2-core 2G server, the memory will be filled up and the memory will freeze. However, if I don’t use the backend, it will not fill up the memory. Is it because the configuration is not enough?

**Comment by ZakiuC** [comment]
我在2核2g的服务器上部署后台后运行会直接占满内存然后卡死，但是不用后台就不会直接拉满占用，是因为配置不够吗？

**Comment by moonrailgun** [comment]
够的。目前的nightly服务就是部署在2g内存的机器上的。

你可以通过如下方式来解决:
- 检查是否有其他应用占据了内存
- 增加交换空间，来解决临时的内存占用

**Comment by ZakiuC** [comment]
> 够的。目前的nightly服务就是部署在2g内存的机器上的。
> 
> 你可以通过如下方式来解决:
> 
> * 检查是否有其他应用占据了内存
> * 增加交换空间，来解决临时的内存占用
> 
> Enough. The current nightly service is deployed on a machine with 2g of memory.
> 
> You can solve it by:
> 
> * Check if there are other applications occupying memory
> * Increase swap space to solve temporary memory usage

谢谢你，我发现我没有开启swap，在开启后使用后台没问题了，但我还有一个问题swap具体开多大适合呢，我看有说开实际内存x2的，所以我开了4g的swap，这对其他程式会有影响吗？

**Comment by moonrailgun** [comment]
没有，swap本身就是一个成熟的解决方案，mac开的swap空间可厉害多了
