### ISSUE TITLE
套了CDN之后无法登陆正常使用，一直在连接服务器 || After setting up the CDN, I cannot log in and use it normally, and I keep connecting to the server.

### ISSUE THREAD

**Issue by OneSoftHaha** [msgbyte/tailchat#156]
如题，CDN为LightCDN，用阿里云+1Panel部署的
![image](https://github.com/msgbyte/tailchat/assets/113611411/80bdbc7c-06d4-4d8b-8099-f9f0b497467b)
登录页面可以显示，在输入账号密码登录后就会卡在这
![image](https://github.com/msgbyte/tailchat/assets/113611411/d8a7e21d-4dfa-45e6-957c-7fb51003b158)
直接访问云服务器ip+端口号则无这个问题

---
As the title says, the CDN is LightCDN, deployed with Alibaba Cloud + 1Panel
![image](https://github.com/msgbyte/tailchat/assets/113611411/80bdbc7c-06d4-4d8b-8099-f9f0b497467b)
The login page can be displayed, but you will be stuck here after entering your account and password to log in.
![image](https://github.com/msgbyte/tailchat/assets/113611411/d8a7e21d-4dfa-45e6-957c-7fb51003b158)
Directly accessing the cloud server IP + port number does not have this problem

**Comment by moonrailgun** [comment]
看文档了么？对于需要cdn的情况需要单独部署前端服务给cdn访问。

https://tailchat.msgbyte.com/docs/deployment/cdn
