### ISSUE TITLE
[feat]: add reload button in system setting

### ISSUE THREAD

**Issue by moonrailgun** [msgbyte/tailchat#159]
helpful for desktop and mobile user

**Comment by Robert-Kramar** [comment]
can you assign me this issue ?

**Comment by moonrailgun** [comment]
Yeah, I'm looking forward to your PR

**Comment by Robert-Kramar** [comment]
Hi, I'm already working on this issue, but I have a question: What exactly needs to be reloaded with this button? Can you please specify what this button should do more clearly?

**Comment by moonrailgun** [comment]
Yeah, thanks for your work. reload button is use for some platform which no refresh.

for example: mobile, and desktop(although desktop can reload with ctrl+r)

And some place in tailchat, its should reload to apply new config, for example change language, or install plugins.
