### ISSUE TITLE
[bug]Windows端无法添加域名服务器，只能使用内网IP || [bug]Domain name server cannot be added on Windows side, only intranet IP can be used

### ISSUE THREAD

**Issue by Cide999** [msgbyte/tailchat#161]
添加域名会失败，在浏览器上能够正常使用，我的域名可以直接在外网访问
![Snipaste_2023-10-22_16-39-31](https://github.com/msgbyte/tailchat/assets/30822042/0f014401-44c5-43a6-b538-80780139fa21)

在网页上使用livekit插件进行语音通话会出现短暂的电音效果，在teamspeak上是正常的

提点建议：
1.希望Windows端不要使用浏览器内核的麦克风，或者对麦克风的驱动进行优化
2.希望能够增加验证码的功能，避免机器人爆破

谢谢！

---
Adding a domain name will fail, but it can be used normally on the browser. My domain name can be accessed directly from the outside network.
![Snipaste_2023-10-22_16-39-31](https://github.com/msgbyte/tailchat/assets/30822042/0f014401-44c5-43a6-b538-80780139fa21)

When using the livekit plug-in for voice calls on a web page, there will be a brief electronic sound effect, which is normal on teamspeak.

Some suggestions:
1. I hope that the Windows side will not use the browser kernel microphone, or the microphone driver will be optimized.
2. Hope that the function of verification code can be added to avoid robot blasting

Thanks!

**Comment by moonrailgun** [comment]
我这里尝试了一下发现没什么问题，确认一下是否是临时的网络的问题呢？

![20231022171210_rec_](https://github.com/msgbyte/tailchat/assets/6964737/05453d40-9501-4b54-b513-06b918d127c8)

为了方便你了解背后的原理以方便测试，我可以告诉你添加服务器的背后使用了那些接口方便自查

- 请求客户端的 `/tailchat.manifest` 接口以获取服务端的地址以及docker镜像版本号
- 请求服务端的`/api/config/client` 接口以获取服务器名称

另外回答你两个问题:
1. windows端本质是对网页端的本地增加，内核本身也是chrome用cpp代码写的获取系统设备输入的。我不确定你说的是否是设备原因，更大的概率是livekit提供的服务器部署在国外，没有对国内网络进行特别的优化，电音是因为网络波动导致的动态补偿导致的。这个在音视频领域其实很常见，如zoom、飞书会议等也经常会出现该问题
2. 如果对这方面的安全有顾虑的话更加建议的方案是在网关层对固定ip请求固定接口的频率做限制而不是在应用层去做，这是一种更加灵活的做法。如果你在这方面有什么收获的话欢迎提交你的技术文章来帮助有同类需要的同学。当然也可以通过开发插件来实现此类需求，但是同样的因为我个人精力有限，没有办法顾及所有人的需求，因此欢迎提交pr

**Comment by Cide999** [comment]
好的，非常感谢你的回答

![Snipaste_2023-10-22_17-43-58](https://github.com/msgbyte/tailchat/assets/30822042/f6f4e8d9-2070-4036-82a9-62f3de375b37)
![Snipaste_2023-10-22_17-43-30](https://github.com/msgbyte/tailchat/assets/30822042/8b351487-4687-468d-8ea5-c2403efcba94)

docker镜像版本号是latest，今天才刚刚部署
![Snipaste_2023-10-22_17-53-29](https://github.com/msgbyte/tailchat/assets/30822042/b47101a2-6f79-458e-b68c-687e72818c64)

电脑的系统是Windows11

如果Windows端只是网页端的本地增加的话，那样是否也会导致程序无法取消界面显示，无法放置在后台当作语音软件来使用？那样的话Windows端的受众可能会更小。
语音出现电音的问题我会尝试改成声网的插件来尝试一下。
对固定IP的请求进行限制只能适用于低层次的黑客吧，一般情况下的爆破都带有跳板，不过我自己想想办法吧，非常感谢你的回复。

**Comment by moonrailgun** [comment]
没听懂什么叫 "导致程序无法取消界面显示".

另外放在后台是可以的

**Comment by Cide999** [comment]
好吧，抱歉，可能是我只能看到一开始的界面，所以误以为不能放后台。
插件换成声网的之后语音效果好了很多。
感谢作者的开源😊

**Comment by Cide999** [comment]
不过我在声网的插件无法在浏览器上直播自己的屏幕，在LiveKit插件就可以，是不是还需要在声网的消息通知服务配置中设置些什么？这个建议写在文档里。

**Comment by moonrailgun** [comment]
我添加了一个issue，回头看一下。

这个先关了
