### ISSUE TITLE
添加后台后访问502 || is accessed after adding the background 502.

### ISSUE THREAD

**Issue by ACnoway** [msgbyte/tailchat#165]
不添加后台时一切正常，加后台后502，报错Bad Gateway

---
Everything is normal without adding the background. After adding the background, 502 is reported. The error Bad Gateway

**Comment by moonrailgun** [comment]
可以尝试重启。大概是因为你启动的方式有问题导致traefik没有很好处理路由关系。可以考虑应用关闭后一起启动起来

**Comment by ACnoway** [comment]
> 可以尝试重启。大概是因为你启动的方式有问题导致traefik没有很好处理路由关系。可以考虑应用关闭后一起启动起来
> 
> You can try restarting. It's probably because there's something wrong with the way you started it that traefik doesn't handle the routing relationship well. You can consider starting the application together after closing it.

使用了`docker compose -f docker-compose.yml -f admin.yml down`然后`docker compose -f docker-compose.yml -f admin.yml up -d`，反复多次还是这样

**Comment by ACnoway** [comment]
现在404了（）

**Comment by moonrailgun** [comment]
请提供更多的信息以确定问题。比如是否存在外部的网关去做拦截导致请求根本没有到tailchat这一层？如果是严格按照官方配置的话不会出现任何部署上的问题

**Comment by ACnoway** [comment]
这是我的nginx配置：

```
server {
    listen 80;
    listen [::]:80;
    charset utf-8;
    server_name chat.imlzhyt.top file-chat.imlzhyt.top;

    location / {
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Range $http_range;
            proxy_set_header If-Range $http_if_range;
        proxy_redirect off;
        proxy_pass http://127.0.0.1:11000;
        # the max size of file to upload
        client_max_body_size 20000m;
    }

}
```

这是我的docker-compose.env

```
LOGGER=true
LOGLEVEL=info
SERVICEDIR=services

TRANSPORTER=redis://redis:6379

REDIS_URL=redis://redis:6379
MONGO_URL=mongodb://mongo/tailchat
SECRET=***

# file
API_URL=https://file-chat.imlzhyt.top

# minio
MINIO_URL=minio:9000
MINIO_USER=tailchat
MINIO_PASS=com.msgbyte.tailchat

# SMTP
SMTP_SENDER=***
SMTP_URI=***

# metrics
PROMETHEUS=1

# Admin
ADMIN_USER=tailchat
ADMIN_PASS=***
```

**Comment by moonrailgun** [comment]
通过反向代理访问该地址指向的是你的主页。你可以先测试能否通过11000端口进行访问

**Comment by ACnoway** [comment]
对不起，忘记看nginx的日志了，刚才发现是apache莫名启动抢占了nginx的80端口，现在没问题了，辛苦了
