### ISSUE TITLE
docker compose部署后/plugins报404

### ISSUE THREAD

**Issue by ACnoway** [msgbyte/tailchat#166]
除了plugins其他都可以正常访问，查询nginx的错误日志未发现报错，查询docker的`tailchat-service-all-plugins-1`日志以及traefik日志都没有报错，实在不知道怎么回事了XP

**Comment by moonrailgun** [comment]
plugins 是指的 服务端的插件还是客户端的插件？

**Comment by ACnoway** [comment]
也许是所有的插件？就是域名/plugins直接404了

**Comment by ACnoway** [comment]
不是全部404，刚刚比对过后发现除了mdpanel之外全部无法访问，返回404，mdpanel返回一个js脚本

**Comment by ACnoway** [comment]
这是all-plugin容器的日志：

**Comment by moonrailgun** [comment]
![image](https://github.com/msgbyte/tailchat/assets/6964737/d25f1938-5ce7-4797-9abf-10a9c7c0762a)

我看没什么问题啊

**Comment by ACnoway** [comment]
离谱，现在好了
