### ISSUE TITLE
何时能自带视频会议的功能啊我看文档还是不支持自带，只能声网之类的。 || When can I bring my own video conferencing function? I read the documentation and it still doesn’t support bringing it in. It can only be done through Shengwang or something like that.

### ISSUE THREAD

**Issue by SaltyFish-scy** [msgbyte/tailchat#186]
何时能自带视频会议的功能啊我看文档还是不支持自带，只能声网之类的。

---
When will the video conferencing function be built in? I read the documentation and it still doesn’t support bringing it in. It can only be done through Shengwang or the like.

**Comment by moonrailgun** [comment]
视频会议是一个可选功能，因为不是每个人都需要视频会议功能。而且流媒体是很复杂的。不能用docker部署
Tailchat的核心是最简化实践然后配上各种插件实现业务

除了声网 官方推荐使用livekit插件

https://tailchat.msgbyte.com/docs/advanced-usage/plugins/com.msgbyte.livekit

**Comment by SaltyFish-scy** [comment]
好的好的，主要现在不确定用声网livekit之类的插件，需要付费吗，我记得当时去声网那一看，是要按时长付费，就很头大。

**Comment by moonrailgun** [comment]
音视频成本很高肯定要收费，只不过基本都有免费时长。
如果你用livekit方案的话，livekit是可以自部署的

**Comment by SaltyFish-scy** [comment]
好吧感谢感谢解答
