### ISSUE TITLE
Can't visit the website though I installed it properly

### ISSUE THREAD

**Issue by infopensource** [msgbyte/tailchat#192]
I have attempted two different methods for installation: using 1panel and deploying via Docker Compose, but unfortunately, neither of them proved successful. When attempting installation through 1panel, it consistently restarts without success. Meanwhile, utilizing Docker Compose results in an inability to access the website. Additionally, when trying to install it using npx, errors occurred, rendering the process unsuccessful.
> Initializing Tailchat configuration and environment variables for you
> ? (FILE_LIMIT)File upload volume limit, the default is 1048576(1m) 10485760000
> ✖ Unexpected initialization of Tailchat with docker
> RequestError: connect ETIMEDOUT 155.248.215.62:443
>     at ClientRequest.<anonymous> (/home/orangepi/.npm/_npx/f46af3e4394b010d/node_modules/got/dist/source/core/index.js:970:111)
>     at Object.onceWrapper (node:events:634:26)
>     at ClientRequest.emit (node:events:531:35)
>     at origin.emit (/home/orangepi/.npm/_npx/f46af3e4394b010d/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
>     at TLSSocket.socketErrorListener (node:_http_client:495:9)
>     at TLSSocket.emit (node:events:519:28)
>     at emitErrorNT (node:internal/streams/destroy:169:8)
>     at emitErrorCloseNT (node:internal/streams/destroy:128:3)
>     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
>     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16) {
>   code: 'ETIMEDOUT',
>   timings: {
>     start: 1703080036099,
>     socket: 1703080036101,
>     lookup: 1703080036104,
>     connect: undefined,
>     secureConnect: undefined,
>     upload: undefined,
>     response: undefined,
>     end: undefined,
>     error: 1703080164789,
>     abort: undefined,
>     phases: {
>       wait: 2,
>       dns: 3,
>       tcp: undefined,
>       tls: undefined,
>       request: undefined,
>       firstByte: undefined,
>       download: undefined,
>       total: 128690
>     }
>   }
> }

**Comment by moonrailgun** [comment]
I don't know why you think you have no way to boot, since from your error report you didn't even successfully download the config file

**Comment by moonrailgun** [comment]
ok, i found download proxy has been down

**Comment by moonrailgun** [comment]
new cli 1.5.14 has been released. i think its maybe fixed

**Comment by infopensource** [comment]
> new cli 1.5.14 has been released. i think its maybe fixed

I have updated, it didn't work.

> orangepi@orangepi5b:/opt/1panel/apps/tailchat$ npx tailchat-cli docker init
> Initializing Tailchat configuration and environment variables for you
> A complete list of environment variables can be accessed at: https://tailchat.msgbyte.com/docs/deployment/environment to learn more
> ? Configurate storage directory (./tailchat) (node:130256) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
> (Use `node --trace-deprecation ...` to show where the warning was created)
> orangepi@orangepi5b:/opt/1panel/apps/tailchat$ npx tailchat-cli docker update
> ⠋ Start updating the image(node:130416) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
> (Use `node --trace-deprecation ...` to show where the warning was created)
> ℹ The remote image has been found, start downloading
> Digest: sha256:8c197ca3a1a578f10543b064fbe1196376419874215c9b4ae91d309161add707
> Status: Image is up to date for moonrailgun/tailchat:latest
> ✓ [latest] Pulling from moonrailgun/tailchat 
> ✔ Digest: sha256:8c197ca3a1a578f10543b064fbe1196376419874215c9b4ae91d309161add707
> ✔ Status: Image is up to date for moonrailgun/tailchat:latest
> ✔ Download image complete
> ℹ Updating image tags
> ✔ The image tag has been updated

> orangepi@orangepi5b:/opt/1panel/apps/tailchat$ npx tailchat-cli docker init
> Initializing Tailchat configuration and environment variables for you
> A complete list of environment variables can be accessed at: https://tailchat.msgbyte.com/docs/deployment/environment to learn more
> ? Configurate storage directory (./tailchat) (node:130680) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
> (Use `node --trace-deprecation ...` to show where the warning was created)
> ? Configurate storage directory ./tailchat
> ? (SECRET)Please enter any string, which will be used as the secret key for Tailchat to sign the user identity. Leaking this string will cause the risk of identity forgery. By default, a 16-digit string is 
> randomly generated 3340ba14b522c872
> ? (API_URL)Please configure an address that can be accessed by the external network, which will affect the storage path and access address of the file, example: https://tailchat.example.com 
> http://
> ? (FILE_LIMIT)File upload volume limit, the default is 1048576(1m) 10485760000
> ✖ Unexpected initialization of Tailchat with docker
> RequestError: write EPROTO 1080C39E7F000000:error:0A000438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1586:SSL alert number 80
> 
>     at ClientRequest.<anonymous> (/home/orangepi/.npm/_npx/f46af3e4394b010d/node_modules/got/dist/source/core/index.js:970:111)
>     at Object.onceWrapper (node:events:634:26)
>     at ClientRequest.emit (node:events:531:35)
>     at origin.emit (/home/orangepi/.npm/_npx/f46af3e4394b010d/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
>     at TLSSocket.socketErrorListener (node:_http_client:495:9)
>     at TLSSocket.emit (node:events:519:28)
>     at emitErrorNT (node:internal/streams/destroy:169:8)
>     at emitErrorCloseNT (node:internal/streams/destroy:128:3)
>     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
>     at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16) {
>   code: 'EPROTO',
>   timings: {
>     start: 1703087731223,
>     socket: 1703087731226,
>     lookup: 1703087731233,
>     connect: 1703087731234,
>     secureConnect: undefined,
>     upload: 1703087731235,
>     response: undefined,
>     end: undefined,
>     error: 1703087731236,
>     abort: undefined,
>     phases: {
>       wait: 3,
>       dns: 7,
>       tcp: 1,
>       tls: undefined,
>       request: 1,
>       firstByte: undefined,
>       download: undefined,
>       total: 13
>     }
>   }
> }
> 

it's the version

> orangepi@orangepi5b:/opt/1panel/apps/tailchat$ npx tailchat-cli --version
> 1.5.14

**Comment by infopensource** [comment]
![image](https://github.com/msgbyte/tailchat/assets/44309311/3f0c9c40-be33-4fb5-8bb9-cf1e039d2737)

**Comment by moonrailgun** [comment]
I think this is a system error. It seems that your server does not support GitHub's https protocol(sslv3). You can try to get the configuration content manually (copy and paste from github).
For specific manual operations, please refer to the official documentation.
