### ISSUE TITLE
Self Hosting?

### ISSUE THREAD

**Issue by prologic** [msgbyte/tailchat#204]
Is this self-hostable? If so I can't find any docs on how to stand up my own instance? 🤔

**Comment by moonrailgun** [comment]
I think it's quite easy to find. Is there any guidance difficulty that prevented you from discovering it? Your feedback will help us solve similar problems

https://tailchat.msgbyte.com/docs/deployment/docker-compose

**Comment by prologic** [comment]
Ahh! I _think_ what tripped me was the "Application Deployment" (_extra word_) and it being 4 layers down. I would have expected to see a "Quick Start" really IMO 😅 But thank you! 🙏
<img width="1712" alt="Screenshot 2024-02-02 at 17 56 51" src="https://github.com/msgbyte/tailchat/assets/1290234/4af340c3-5585-475c-b554-56fe3dc229a6">

**Comment by prologic** [comment]
It looks like the [Manually install from public images](https://tailchat.msgbyte.com/docs/deployment/docker-compose#startup-project) section mentioned `wget`'ing a set of `docker-compose.yml` and `docker-compose.env` but the Docker COmpose config doesn't _actually_ refernece upstream images at all :/

**Comment by moonrailgun** [comment]
![image](https://github.com/msgbyte/tailchat/assets/6964737/7bf0388b-761f-431c-bf6e-b005bd6fa5d4)

did you run it?

**Comment by prologic** [comment]
Thank you! I got a local (_on my desktop_) version working and had a bit of a play. It's a bit different, but most things work fairly well 👌
