### ISSUE TITLE
tailchat桌面软件依然存在工具栏 || tailchat desktop software still has a toolbar

### ISSUE THREAD

**Issue by Anjiurine** [msgbyte/tailchat#207]
如题

---
As the title

**Comment by moonrailgun** [comment]
？

**Comment by Anjiurine** [comment]
> ？

electron自带的那个原生工具栏，我在代码里看到那玩意儿实际上已经关了，但是在目前的发布版本中还是有的，很丑

**Comment by moonrailgun** [comment]
did you taking about title bar?
i think its always display in main view(not select server view).

Did you has any idea about it? i think its useful

**Comment by Anjiurine** [comment]
> did you taking about title bar?
> i think its always display in main view(not select server view).
> 
> Did you has any idea about it? i think its useful

不，这并不是标题栏。我指的是electron原生的顶部工具栏，就是窗口顶部的那个。这是我在desktop客户端0.1.0中发现的

**Comment by Anjiurine** [comment]
就像这样
![image](https://github.com/msgbyte/tailchat/assets/147403913/ac064461-d899-45d9-ba76-47d917d0a4c2)

**Comment by Anjiurine** [comment]
这应该是一个子进程，而这个进程的工具栏没有被关闭

**Comment by moonrailgun** [comment]
I dont know but i think menu bar its useful

**Comment by moonrailgun** [comment]
did you have any idea?

**Comment by Anjiurine** [comment]
> did you have any idea?

我认为这个菜单栏在tailchat目前的情况下应该是没有作用的，它应该像webapp的tailchat那样被隐藏，因为它真的很丑
![image](https://github.com/msgbyte/tailchat/assets/147403913/17d02c1a-85fd-4b11-a481-e82e1f72c388)

**Comment by Anjiurine** [comment]
> > did you have any idea?
> 
> 我认为这个菜单栏在tailchat目前的情况下应该是没有作用的，它应该像webapp的tailchat那样被隐藏，因为它真的很丑 ![image](https://private-user-images.githubusercontent.com/147403913/304337661-17d02c1a-85fd-4b11-a481-e82e1f72c388.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MTIzNjQsIm5iZiI6MTcwNzgxMjA2NCwicGF0aCI6Ii8xNDc0MDM5MTMvMzA0MzM3NjYxLTE3ZDAyYzFhLTg1ZmQtNGIxMS1hNDgxLWU4MmUxZjcyYzM4OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxM1QwODE0MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZjQ2ZGNmMjhiYmUyOWQ1NWEwZWUzZDk1ZDJlN2FjZDg3MzUxYzEyNjNjMjNiNWJmMGM1Yjc1MGY0MzEwYzZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NLmmWPN6BAok2kOvmH7wdXekURYH-7UaQK3u50JDErk)就这个webapp这样隐藏菜单栏

**Comment by Anjiurine** [comment]
> > > did you have any idea?
> > 
> > 
> > 我认为这个菜单栏在tailchat目前的情况下应该是没有作用的，它应该像webapp的tailchat那样被隐藏，因为它真的很丑 ![image](https://private-user-images.githubusercontent.com/147403913/304337661-17d02c1a-85fd-4b11-a481-e82e1f72c388.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MTIzNjQsIm5iZiI6MTcwNzgxMjA2NCwicGF0aCI6Ii8xNDc0MDM5MTMvMzA0MzM3NjYxLTE3ZDAyYzFhLTg1ZmQtNGIxMS1hNDgxLWU4MmUxZjcyYzM4OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxM1QwODE0MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZjQ2ZGNmMjhiYmUyOWQ1NWEwZWUzZDk1ZDJlN2FjZDg3MzUxYzEyNjNjMjNiNWJmMGM1Yjc1MGY0MzEwYzZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NLmmWPN6BAok2kOvmH7wdXekURYH-7UaQK3u50JDErk)就这个webapp这样隐藏菜单栏
> 
> > > did you have any idea?
> > 
> > 
> > I think this menu bar should be useless in the current situation of tailchat, it should be hidden like tailchat of webapp, because it is really ugly
![image](https://private-user-images.githubusercontent .com/147403913/304337661-17d02c1a-85fd-4b11-a481-e82e1f72c388.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVk IjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MTIzNjQsIm5iZiI6MTcwNzgxMjA2NCwicGF0aCI6Ii8xNDc0MDM5MTMvMzA0MzM3NjYxLTE3ZDAyY zFhLTg1ZmQtNGIxMS1hNDgxLWU4MmUxZjcyYzM4OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMj QwMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxM1QwODE0MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZjQ2ZGN mMjhiYmUyOWQ1NWEwZWUzZDk1ZDJlN2FjZDg3MzUxYzEyNjNjMjNiNWJmMGM1Yjc1MGY0MzEwYzZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJ nJlcG9faWQ9MCJ9.NLmmWPN6BAok2kOvmH7wdXekURYH-7UaQK3u50JDErk) This webapp hides the menu bar like this

**Comment by Anjiurine** [comment]
> > > > did you have any idea?
> > > 
> > > 
> > > 我认为这个菜单栏在tailchat目前的情况下应该是没有作用的，它应该像webapp的tailchat那样被隐藏，因为它真的很丑 ![image](https://private-user-images.githubusercontent.com/147403913/304337661-17d02c1a-85fd-4b11-a481-e82e1f72c388.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MTIzNjQsIm5iZiI6MTcwNzgxMjA2NCwicGF0aCI6Ii8xNDc0MDM5MTMvMzA0MzM3NjYxLTE3ZDAyYzFhLTg1ZmQtNGIxMS1hNDgxLWU4MmUxZjcyYzM4OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxM1QwODE0MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZjQ2ZGNmMjhiYmUyOWQ1NWEwZWUzZDk1ZDJlN2FjZDg3MzUxYzEyNjNjMjNiNWJmMGM1Yjc1MGY0MzEwYzZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NLmmWPN6BAok2kOvmH7wdXekURYH-7UaQK3u50JDErk)就这个webapp这样隐藏菜单栏
> > 
> > 
> > > > did you have any idea?
> > > 
> > > 
 I think this menu bar should be useless in the current situation of tailchat, it should be hidden like tailchat of webapp, because it is really ugly
![image](https://private-user-images.githubusercontent .com/147403913/304337661-17d02c1a-85fd-4b11-a481-e82e1f72c388.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVk IjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MTIzNjQsIm5iZiI6MTcwNzgxMjA2NCwicGF0aCI6Ii8xNDc0MDM5MTMvMzA0MzM3NjYxLTE3ZDAyY zFhLTg1ZmQtNGIxMS1hNDgxLWU4MmUxZjcyYzM4OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMj QwMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxM1QwODE0MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZjQ2ZGN mMjhiYmUyOWQ1NWEwZWUzZDk1ZDJlN2FjZDg3MzUxYzEyNjNjMjNiNWJmMGM1Yjc1MGY0MzEwYzZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJ nJlcG9faWQ9MCJ9.NLmmWPN6BAok2kOvmH7wdXekURYH-7UaQK3u50JDErk) This webapp hides the menu bar like this

**Comment by Anjiurine** [comment]
> > > > > did you have any idea?
> > > > 
我认为这个菜单栏在tailchat目前的情况下应该是没有作用的，它应该像webapp的tailchat那样被隐藏，因为它真的很丑 ![image](https://private-user-images.githubusercontent.com/147403913/304337661-17d02c1a-85fd-4b11-a481-e82e1f72c388.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MTIzNjQsIm5iZiI6MTcwNzgxMjA2NCwicGF0aCI6Ii8xNDc0MDM5MTMvMzA0MzM3NjYxLTE3ZDAyYzFhLTg1ZmQtNGIxMS1hNDgxLWU4MmUxZjcyYzM4OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxM1QwODE0MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZjQ2ZGNmMjhiYmUyOWQ1NWEwZWUzZDk1ZDJlN2FjZDg3MzUxYzEyNjNjMjNiNWJmMGM1Yjc1MGY0MzEwYzZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NLmmWPN6BAok2kOvmH7wdXekURYH-7UaQK3u50JDErk)就这个webapp这样隐藏菜单栏
> > > 
> > > 
> > > > > did you have any idea?
> 
> I think this menu bar should be useless in the current situation of tailchat, it should be hidden like tailchat of webapp, because it is really ugly ![image](https://private-user-images.githubusercontent .com/147403913/304337661-17d02c1a-85fd-4b11-a481-e82e1f72c388.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVk IjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MTIzNjQsIm5iZiI6MTcwNzgxMjA2NCwicGF0aCI6Ii8xNDc0MDM5MTMvMzA0MzM3NjYxLTE3ZDAyY zFhLTg1ZmQtNGIxMS1hNDgxLWU4MmUxZjcyYzM4OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMj QwMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxM1QwODE0MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZjQ2ZGN mMjhiYmUyOWQ1NWEwZWUzZDk1ZDJlN2FjZDg3MzUxYzEyNjNjMjNiNWJmMGM1Yjc1MGY0MzEwYzZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJ nJlcG9faWQ9MCJ9.NLmmWPN6BAok2kOvmH7wdXekURYH-7UaQK3u50JDErk) This webapp hides the menu bar like this

**Comment by Anjiurine** [comment]
>did you have any idea?
我认为这个菜单栏在tailchat目前的情况下应该是没有作用的，它应该像webapp的tailchat那样被隐藏，因为它真的很丑 ![image](https://private-user-images.githubusercontent.com/147403913/304337661-17d02c1a-85fd-4b11-a481-e82e1f72c388.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MTIzNjQsIm5iZiI6MTcwNzgxMjA2NCwicGF0aCI6Ii8xNDc0MDM5MTMvMzA0MzM3NjYxLTE3ZDAyYzFhLTg1ZmQtNGIxMS1hNDgxLWU4MmUxZjcyYzM4OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxM1QwODE0MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZjQ2ZGNmMjhiYmUyOWQ1NWEwZWUzZDk1ZDJlN2FjZDg3MzUxYzEyNjNjMjNiNWJmMGM1Yjc1MGY0MzEwYzZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NLmmWPN6BAok2kOvmH7wdXekURYH-7UaQK3u50JDErk)就这个webapp这样隐藏菜单栏
>  did you have any idea?
I think this menu bar should be useless in the current situation of tailchat, it should be hidden like tailchat of webapp, because it is really ugly ![image](https://private-user-images.githubusercontent .com/147403913/304337661-17d02c1a-85fd-4b11-a481-e82e1f72c388.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVk IjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MTIzNjQsIm5iZiI6MTcwNzgxMjA2NCwicGF0aCI6Ii8xNDc0MDM5MTMvMzA0MzM3NjYxLTE3ZDAyY zFhLTg1ZmQtNGIxMS1hNDgxLWU4MmUxZjcyYzM4OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMj QwMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxM1QwODE0MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZjQ2ZGN mMjhiYmUyOWQ1NWEwZWUzZDk1ZDJlN2FjZDg3MzUxYzEyNjNjMjNiNWJmMGM1Yjc1MGY0MzEwYzZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJ nJlcG9faWQ9MCJ9.NLmmWPN6BAok2kOvmH7wdXekURYH-7UaQK3u50JDErk) This webapp hides the menu bar like this
