### ISSUE TITLE
Fail to set up a dev env for desktop app.

### ISSUE THREAD

**Issue by 1622145167** [msgbyte/tailchat#208]
After running `npm i` and `npm start` in `client/desktop`, it can't load the web page.
![image](https://github.com/msgbyte/tailchat/assets/54617326/32809922-ff71-4a6b-9dc3-1f49c0a429a7)
Error info is uploaded below.
[localhost-1707636408601.log](https://github.com/msgbyte/tailchat/files/14231638/localhost-1707636408601.log)
Help needed. Thanks.

**Comment by 1622145167** [comment]
> did you install desktop dependencies with `yarn`?

Uhh...No, according to [`client/desktop/README.md`](https://github.com/msgbyte/tailchat/tree/master/client/desktop#install ). Is there any differences?

**Comment by moonrailgun** [comment]
This `README.md` is generated by boilerplate.

because of this package has `yarn.lock` file so you better use `yarn` to manage dependency and make sure dependencies's version is same
