### ISSUE TITLE
添加右键菜单后一堆相关问题 || A bunch of related questions after adding the right-click menu

### ISSUE THREAD

**Issue by shenjackyuanjie** [msgbyte/tailchat#215]
1. 图片无法右键保存 (fix in #214 )
2. 链接无法右键后在新窗口内打开
  1. 或者说链接打开方式有问题，不应该让链接在服务器网页内打开

---
1. Pictures cannot be saved by right-clicking (fix in #214)
2. The link cannot be opened in a new window after right-clicking.
  1. Or there is a problem with the link opening method, and the link should not be opened in the server web page.

**Comment by moonrailgun** [comment]
already fixed in a02ad80bf177b1c6086e9c6150df744ba2027b84

**Comment by shenjackyuanjie** [comment]
看起来没啥新问题了（
closed！

**Comment by moonrailgun** [comment]
cool
