### ISSUE TITLE
ELIFECYCLE  Command failed with exit code 2. 

### ISSUE THREAD

**Issue by 982901760** [msgbyte/tailchat#229]
server                                   |  WARN  The field "pnpm" was found in /www/wwwroot/msgbyte/tailchat/server/package.json. This will not take effect. You
 should configure "pnpm" at the root of the workspace instead.                                                                                                   
Scope: all 76 workspace projects                                                                                                                                 
Lockfile is up to date, resolution step is skipped                                                                                                               
Already up to date                                                                                                                                               
 WARN  Failed to create bin at /www/wwwroot/msgbyte/tailchat/server/plugins/com.msgbyte.getui/node_modules/.bin/tailchat-runner. ENOENT: no such file or director
y, open '/www/wwwroot/msgbyte/tailchat/server/packages/sdk/dist/runner/cli.js'                                                                                   
 WARN  Failed to create bin at /www/wwwroot/msgbyte/tailchat/server/plugins/com.msgbyte.prettyinvite/node_modules/.bin/tailchat-runner. ENOENT: no such file or d
irectory, open '/www/wwwroot/msgbyte/tailchat/server/packages/sdk/dist/runner/cli.js'                                                                            
 WARN  Failed to create bin at /www/wwwroot/msgbyte/tailchat/server/node_modules/.bin/tailchat-service-openapi-generator. ENOENT: no such file or directory, open
 '/www/wwwroot/msgbyte/tailchat/server/packages/openapi-generator/dist/index.js'                                                                                 
 WARN  Failed to create bin at /www/wwwroot/msgbyte/tailchat/server/node_modules/.bin/tailchat-service-swagger-generator. ENOENT: no such file or directory, open
 '/www/wwwroot/msgbyte/tailchat/server/packages/swagger-jsdoc-generator/dist/index.js'                                                                           
 WARN  12 other warnings                                                                                                                                         
client/packages/tailchat-client-sdk prepare$ tsc                                                                                                                 
│ src/openapi/client/ws.ts(4,34): error TS2307: Cannot find module 'tailchat-types' or its corresponding type declarations.                                      
└─ Failed in 3.4s at /www/wwwroot/msgbyte/tailchat/client/packages/tailchat-client-sdk                                                                           
apps/github-app prepare$ tsc                                                                                                                                     
└─ Running...                                                                                                                                                    
.../plugin-declaration-generator prepare$ tsc                                                                                                                    
└─ Running...                                                                                                                                                    
packages/types prepare$ pnpm build                                                                                                                               
│ > tailchat-types@1.0.4 build /www/wwwroot/msgbyte/tailchat/packages/types                                                                                      
│ > concurrently npm:build-cjs npm:build-esm                                                                                                                     
│ [build-cjs]                                                                                                                                                    
│ [build-cjs] > tailchat-types@1.0.4 build-cjs                                                                                                                   
│ [build-cjs] > rimraf ./dist/cjs && tsc --outDir dist/cjs                                                                                                       
│ [build-cjs]                                                                                                                                                    
└─ Running...                                                                                                                                                    
server/packages/swagger-jsdoc-generator prepare$ tsc                                                                                                             
└─ Running...                                                                                                                                                    
 ELIFECYCLE  Command failed with exit code 2.

**Comment by moonrailgun** [comment]
did you use pnpm@8?

**Comment by mint-pz** [comment]
> Cannot find module 'tailchat-types' or its

I was using pnpm@9 and confirm using pnpm@8 solved the problem

**Comment by moonrailgun** [comment]
ok cool
