### ISSUE TITLE
私信建立多人会话时报“没有获取会话信息权限” || When establishing a multi-person session via private message, it says "No permission to obtain session information"

### ISSUE THREAD

**Issue by qianglchina** [msgbyte/tailchat#230]
版本：1.11.3
环境变量设置为：
      DISABLE_USER_REGISTER: "true"
      DISABLE_GUEST_LOGIN: "true"
      DISABLE_CREATE_GROUP: "true"

通过日志追踪，原因大致：为“如果创建的是一个多人会话(非双人), 发送系统消息“ 导致的报错

/server/services/core/chat/converse.service.ts 112

---
Version: 1.11.3
The environment variables are set to:
      DISABLE_USER_REGISTER: "true"
      DISABLE_GUEST_LOGIN: "true"
      DISABLE_CREATE_GROUP: "true"

Through log tracking, the reason is roughly: "If a multi-person session (not two-person) is created, send a system message".

/server/services/core/chat/converse.service.ts 112

**Comment by moonrailgun** [comment]
Thanks for your report. i will check it
