### ISSUE TITLE
Office E5邮箱 SMTP无法登陆

### ISSUE THREAD

**Issue by SharwOrange** [msgbyte/tailchat#232]
![图片](https://github.com/msgbyte/tailchat/assets/65716524/f8eed432-744f-45fe-a664-5bc95ea9f909)
如图，使用的是Office E5邮箱（也就是Microsoft E5 开发者）
![图片](https://github.com/msgbyte/tailchat/assets/65716524/febf66af-a336-4b55-b490-a26d8362519d)
配置文件中SMTP配置如下

**Comment by moonrailgun** [comment]
idk but maybe you should using `smtps` protocol.

and did you sure your password is correct?

**Comment by SharwOrange** [comment]
I changed the protocol to `smtps` and it still didn't work
and i sure password is correct

**Comment by moonrailgun** [comment]
feel free to test with `tailchat smtp verify` before you real start tailchat

you can learn more about smtp config here: https://tailchat.msgbyte.com/docs/deployment/smtp#auxiliary-testing-using-cli

**Comment by SharwOrange** [comment]
![图片](https://github.com/msgbyte/tailchat/assets/65716524/c0fdb2fa-b96e-424d-b4eb-d3960d6faecc)
but it still didn't actually work

**Comment by SharwOrange** [comment]
and,i try `tailchat smtp test `
![图片](https://github.com/msgbyte/tailchat/assets/65716524/d0bb25d3-eebf-4317-8ee6-d26f2e66f9b7)
![图片](https://github.com/msgbyte/tailchat/assets/65716524/1f39294d-66a5-4003-ac98-383879eea213)

**Comment by moonrailgun** [comment]
looks weird. i will log more info for your case to invest the reason

**Comment by moonrailgun** [comment]
is releasing 1.11.4, you can upgrade to this version and get more context for fail reason.

**Comment by SharwOrange** [comment]
很怪，但现在更新到1.11.4之后能够发送邮件，配置文件也没做出过改动

It's strange, but now I can send emails after updating to 1.11.4, and the configuration file has not been changed

![图片](https://github.com/msgbyte/tailchat/assets/65716524/a459be69-2be6-4dca-bddc-bec9b9ada1ef)
![图片](https://github.com/msgbyte/tailchat/assets/65716524/7f4af45a-441e-4c3c-b444-4c7e746bd1ac)

**Comment by moonrailgun** [comment]
interesting. idk. but fine.

**Comment by SharwOrange** [comment]
~~🤣我现在才发现我一开始用户名输错了，我憨批一个~~
