### ISSUE TITLE
尝试编译前端时报错 || An error occurred when trying to compile the front end

### ISSUE THREAD

**Issue by OneSoftHaha** [msgbyte/tailchat#234]
如题，在根据[文档](https://tailchat.msgbyte.com/zh-Hans/docs/deployment/cdn)尝试编译前端时报错
我尝试在我的UbuntuServer和Windows上编译，均无法编译成功，且都报相同的错误
附上编译时的日志
[logs.txt](https://github.com/user-attachments/files/15741587/logs.txt)

---
As the title states, an error occurs when trying to compile the front end according to [Document](https://tailchat.msgbyte.com/zh-Hans/docs/deployment/cdn)
I tried to compile on my UbuntuServer and Windows, but failed to compile successfully and reported the same error.
Attached is the compile time log
[logs.txt](https://github.com/user-attachments/files/15741587/logs.txt)

**Comment by moonrailgun** [comment]
did you use pnpm@8? because pnpm have some break change in 9 and not support yet

**Comment by OneSoftHaha** [comment]
确实是pnpm9的问题，用pnpm8就编译成功了，谢谢
