### ISSUE TITLE
私信列表过多会卡死 || If there are too many private message lists, it will freeze.

### ISSUE THREAD

**Issue by NaclFire** [msgbyte/tailchat#239]
当私信太多的时候，打开页面会一直加载中，私信列表也一直显示不全

---
When there are too many private messages, the opening page will keep loading, and the private message list will always be incomplete.

**Comment by moonrailgun** [comment]
are you talking about friend list?

**Comment by NaclFire** [comment]
> are you talking about friend list?

yes

**Comment by moonrailgun** [comment]
same with issue #238. you can watch that one, i will close this issue.
