### ISSUE TITLE
TC的好友列表出现这个怎么解决？ || TC’s friend list appears. How to solve this problem?

### ISSUE THREAD

**Issue by Github-DHEnry** [msgbyte/tailchat#240]
![image](https://github.com/user-attachments/assets/5e293981-6bad-42b9-89d2-902e759b89e5)
这样咋解决

---
![image](https://github.com/user-attachments/assets/5e293981-6bad-42b9-89d2-902e759b89e5)
How to solve this problem?

**Comment by moonrailgun** [comment]
can you provide more information? for example console log in devtools.

you can open it with F12
