### ISSUE TITLE
使用 从公共镜像中手动安装 方式安装tailchat会安装失败 || If you install tailchat manually from a public image, the installation will fail.

### ISSUE THREAD

**Issue by Github-DHEnry** [msgbyte/tailchat#244]
root@ser455734186792:/home/data# docker pull moonrailgun/tailchat
Using default tag: latest
latest: Pulling from moonrailgun/tailchat
96526aa774ef: Retrying in 1 second
824de1d006d4: Retrying in 1 second
76c34934b331: Retrying in 1 second
fdef87f136ff: Waiting
2ef48c88590d: Waiting
4f4fb700ef54: Waiting
f2b75bfb1693: Waiting
55f564286535: Waiting
d2b2b05dd1ff: Waiting
9a8b728d807b: Waiting
ec625ecd8775: Waiting
2b7a9f68c0f8: Waiting
f385ccecc17a: Waiting
e97628d6751d: Waiting
7c344f577449: Waiting
c258ba7442aa: Waiting
8e5af197497f: Waiting
dd251d891643: Waiting
f0e8b6f75186: Waiting
1076429e9248: Waiting
b45c1dbdc9b5: Waiting
462c874d91a3: Waiting
84cf8274773f: Waiting
7c3c1740ca02: Waiting
error pulling image configuration: download failed after attempts=6: dial tcp 52.58.1.161:443: i/o timeout
不知道为什么会报错，百度的方法都没用
（请使用中文回答我）

---
root@ser455734186792:/home/data# docker pull moonrailgun/tailchat
Using default tag: latest
latest: Pulling from moonrailgun/tailchat
96526aa774ef: Retrying in 1 second
824de1d006d4: Retrying in 1 second
76c34934b331: Retrying in 1 second
fdef87f136ff: Waiting
2ef48c88590d: Waiting
4f4fb700ef54: Waiting
f2b75bfb1693: Waiting
55f564286535: Waiting
d2b2b05dd1ff: Waiting
9a8b728d807b: Waiting
ec625ecd8775: Waiting
2b7a9f68c0f8: Waiting
f385ccecc17a: Waiting
e97628d6751d: Waiting
7c344f577449: Waiting
c258ba7442aa: Waiting
8e5af197497f: Waiting
dd251d891643: Waiting
f0e8b6f75186: Waiting
1076429e9248: Waiting
b45c1dbdc9b5: Waiting
462c874d91a3: Waiting
84cf8274773f: Waiting
7c3c1740ca02: Waiting
error pulling image configuration: download failed after attempts=6: dial tcp 52.58.1.161:443: i/o timeout
I don’t know why the error is reported. Baidu’s methods are useless.
(Please answer me in Chinese)

**Comment by moonrailgun** [comment]
network problem. please check how to use docker in china mainland or change server to oversea

**Comment by Github-DHEnry** [comment]
我香港的服务器，而且怎么解决网络问题

**Comment by Github-DHEnry** [comment]
能不能回复中文
