### ISSUE TITLE
Tailchat Nightly部分群组和私聊会出现黑白色的bug || Tailchat Nightly has black and white bugs in some groups and private chats

### ISSUE THREAD

**Issue by Github-DHEnry** [msgbyte/tailchat#252]
不知道如何解决
![image](https://github.com/user-attachments/assets/e364bbf0-138f-4e86-bde6-4325f0860e4d)

---
Don't know how to solve it
![image](https://github.com/user-attachments/assets/e364bbf0-138f-4e86-bde6-4325f0860e4d)

**Comment by moonrailgun** [comment]
any trigger? maybe because some group added style css code and change global style?

maybe you can share me which group id will make browser looks like this?

**Comment by wyf9** [comment]
I think someone sent message like:
```
[md]
<style type="text/css">
html {
  filter:grayscale(100%);
  -webkit-filter:grayscale(100%);
  -moz-filter:grayscale(100%);
  -ms-filter:grayscale(100%);
  -o-filter:grayscale(100%);
 filter:progid:DXImageTransform.Microsoft.BasicImage(grayscale=1);
  -webkit-filter:grayscale(1)
}
</style>
[/md]
```

It looks like:

![image](https://github.com/user-attachments/assets/80fd357e-dc67-4fac-857a-e0baedb68d13)

> can send message below to resolve (or change current group):

```
[md]
<style type="text/css">
html {
  filter:grayscale(0%);
  -webkit-filter:grayscale(0%);
  -moz-filter:grayscale(0%);
  -ms-filter:grayscale(0%);
  -o-filter:grayscale(0%);
 filter:progid:DXImageTransform.Microsoft.BasicImage(grayscale=0);
  -webkit-filter:grayscale(0)
}
</style>
[/md]
```

**Comment by moonrailgun** [comment]
ok interesting. i will fix it.

**Comment by wyf9** [comment]
![image](https://github.com/user-attachments/assets/9c80ddb6-c1b9-48e5-a8b6-45a2b2782576)

you can limit markdown feature in tailchat, like disable <html> tag.
