### ISSUE TITLE
Configuration in docker-compose.env is not working

### ISSUE THREAD

**Issue by RealfuRyZ** [msgbyte/tailchat#260]
I modified the docker-compose.env file and added the following lines:
```
#SystemConfig
DISABLE_GUEST_LOGIN=1
DISABLE_CREATE_GROUP=1
EMAIL_VERIFY=1
```
After restarting the container orchestration, I found that guest login is still possible when accessing the application again. Is there something I didn’t configure correctly?

![image](https://github.com/user-attachments/assets/11dd5fa2-903e-4722-ba8f-b10e1d3b20b0)
![image](https://github.com/user-attachments/assets/8a9e9103-fa43-4f38-a99a-53b546daad03)

**Comment by RealfuRyZ** [comment]
I just conducted a test, and it seems that restarting the container orchestration is ineffective. The changes only take effect after recreating the containers.so closed

**Comment by moonrailgun** [comment]
because we have some cache in redis.

if you change env, maybe you can manual clear cache in admin or maunal.

i mention it in document, i think.

**Comment by RealfuRyZ** [comment]
> 因为我们在 Redis 中有一些缓存。
> 
> 如果你更改了 env，也许你可以在 admin 或 maunal 中手动清除缓存。
> 
> 我想，我在 document 中提到了它。

understand, thank you for your reply.
