### ISSUE TITLE
环境变量相关问题 || Environment variable related issues

### ISSUE THREAD

**Issue by ods-im** [msgbyte/tailchat#261]
部署环境：群晖 synology NAS 7.2.1
![微信图片_20240929004728](https://github.com/user-attachments/assets/fee03637-3169-452f-b853-2311c3c259f1)
运行无报错，但是访问报错。
采用官方配置在docker compose 文件的  service-all-plugins下面增加了声网相关环境变量。
![微信图片_20240929004920](https://github.com/user-attachments/assets/a1d1215a-f70b-4ad5-9016-cad067a97ed8)

后台访问报错：全局配置加载错误。
![1](https://github.com/user-attachments/assets/20a94a25-b131-45a5-8369-446c8ef0aa23)
![2](https://github.com/user-attachments/assets/33310cfa-ede9-4a68-8fa7-47c28d203f9e)

问题：
1，全局配置加载错误是.env文件报错引起的还是哪里？我该怎么解决
2，插件相关的环境变量（比如声网相关的环境变量）需要添加在哪个地方？

ps;在第一次部署的时候没有出现任何问题，完美运行，然后增加了声网环境变量后再也不能正确访问使用，再恢复初始的也无法正常运行了。

谢谢，感谢作者的开发奉献！

---
Deployment environment: Synology NAS 7.2.1
![WeChat picture_20240929004728](https://github.com/user-attachments/assets/fee03637-3169-452f-b853-2311c3c259f1)
No errors are reported when running, but errors are reported when accessing.
Use the official configuration to add Agora-related environment variables under service-all-plugins in the docker compose file.
![WeChat picture_20240929004920](https://github.com/user-attachments/assets/a1d1215a-f70b-4ad5-9016-cad067a97ed8)

Background access error: Global configuration loading error.
![1](https://github.com/user-attachments/assets/20a94a25-b131-45a5-8369-446c8ef0aa23)
![2](https://github.com/user-attachments/assets/33310cfa-ede9-4a68-8fa7-47c28d203f9e)

question:
1. Is the global configuration loading error caused by the .env file error or where? how can i solve
2. Where do plug-in related environment variables (such as those related to Agora) need to be added?

ps; There were no problems during the first deployment and it ran perfectly. Then after adding the Shengwang environment variable, it could no longer be accessed and used correctly, and it could not run normally again after restoring it to the original one.

Thank you, thank you to the author for his development dedication!

**Comment by moonrailgun** [comment]
> 1，全局配置加载错误是.env文件报错引起的还是哪里？我该怎么解决

这个问题是因为服务器没有办法正常访问导致的。也许你可以尝试重启traefik组件，或者完整执行 `docker compose down` => `docker compose up -d` 来完整恢复状态

> 2，插件相关的环境变量（比如声网相关的环境变量）需要添加在哪个地方？

建议是在环境变量文件中统一添加，这样你就不需要关系具体是哪个模块需要

参考官方文档: [https://tailchat.msgbyte.com/docs/deployment/environment](https://tailchat.msgbyte.com/docs/deployment/environment)

**Comment by ods-im** [comment]
谢谢

> > 1，全局配置加载错误是.env文件报错引起的还是哪里？我该怎么解决
> 
> 这个问题是因为服务器没有办法正常访问导致的。也许你可以尝试重启traefik组件，或者完整执行 `docker compose down` => `docker compose up -d` 来完整恢复状态
> 
> > 2，插件相关的环境变量（比如声网相关的环境变量）需要添加在哪个地方？
> 
> 建议是在环境变量文件中统一添加，这样你就不需要关系具体是哪个模块需要
> 
> 参考官方文档: https://tailchat.msgbyte.com/docs/deployment/environment
> 
> > 1. Is the global configuration loading error caused by the .env file error or where? how can i solve
> 
> This problem is caused by the server not being able to access normally. Maybe you can try restarting the traefik component, or completely execute `docker compose down` => `docker compose up -d` to completely restore the state
> 
> > 2. Where do plug-in related environment variables (such as Agora-related environment variables) need to be added?
> 
> It is recommended to add them uniformly in the environment variable file, so that you do not need to worry about which module requires it.
> 
> Refer to the official documentation: https://tailchat.msgbyte.com/docs/deployment/environment

谢谢，请关闭

**Comment by YInJunWen** [comment]
I encountered the same issue as you. The root cause is that Koa.js requires a middleware to handle the body content when parsing JSON data. If you're unable to resolve this, I recommend using the Express framework. Older versions of Express had the same problem as Koa.js, but in the latest version, they have integrated the solution internally. Therefore, you can use it quite easily and obtain the information after the bot is @-mentioned.
