### ISSUE TITLE
nginx反向代理之后登录会显示”正在连接到聊天服务器“ || nginx reverse proxy, logging in will show "Connecting to chat server"

### ISSUE THREAD

**Issue by neikumao** [msgbyte/tailchat#265]
我想要实现内网语音通话，所以我选了livekit，然后我发现需要使用https才可以使用麦克风，所以我用nginx反向代理之后登录会显示”正在连接到聊天服务器“
![image](https://github.com/user-attachments/assets/167747cb-93c7-4b44-96b4-2741b26c963e)

---
I wanted to implement intranet voice calls, so I chose livekit, and then I found that I needed to use https to use the microphone, so I used nginx reverse proxy and after logging in, it showed "Connecting to chat server"
![image](https://github.com/user-attachments/assets/167747cb-93c7-4b44-96b4-2741b26c963e)
After

**Comment by moonrailgun** [comment]
Check here

https://tailchat.msgbyte.com/docs/deployment/troubleshooting#the-websocket-connection-access-is-incorrect-the-manifestation-is-that-it-can-be-registered-but-the-main-interface-cannot-be-opened

**Comment by neikumao** [comment]
好了，非常感谢
