### ISSUE TITLE
未知原因导致图片上传失败

### ISSUE THREAD

**Issue by lanbinshijie** [msgbyte/tailchat#28]
这个聊天所有的图片功能都失效了，包括头像和日常聊天的图片，请问是有什么需要设置的吗？这是我的调试截图
![截图](https://user-images.githubusercontent.com/62149873/162339274-16fd9fac-49a9-4b9a-ab96-4d5ad53a9a78.png)

**Comment by moonrailgun** [comment]
麻烦确认一下是不是服务端环境变量配置不对。

需要在服务端对外暴露外部可访问的地址
```
API_URL=
```

默认是`http://127.0.0.1:${port}`

**Comment by lanbinshijie** [comment]
> 麻烦确认一下是不是服务端环境变量配置不对。
> 
> 需要在服务端对外暴露外部可访问的地址
> 
> ```
> API_URL=
> ```
> 
> 默认是`http://127.0.0.1:${port}`

抱歉，请问具体是怎么做呢？服务端的API已经可以访问了，消息发送也正常，只有图片功能失效。

**Comment by lanbinshijie** [comment]
好的，感谢，我去试试

**Comment by lanbinshijie** [comment]
搞定了，非常感谢，希望文档能够更详细一些！真的非常好用

**Comment by lanbinshijie** [comment]
搞定了，非常感谢，希望文档能够更详细一些！真的非常好用
