### ISSUE TITLE
没有及时反应

### ISSUE THREAD

**Issue by for-the-zero** [msgbyte/tailchat#40]
当我删除/反应一条消息时，界面不会立即作出反应，需要刷新网页

**Comment by moonrailgun** [comment]
![20220801165312](https://user-images.githubusercontent.com/6964737/182111574-498c93e4-d84b-4100-b274-70c7c4d4d886.gif)

我这边试了一下并不会，检查一下是不是网络问题呢？

**Comment by moonrailgun** [comment]
因为长时间没有回复，我先关了
