### ISSUE TITLE
功能缺失/字体错误

### ISSUE THREAD

**Issue by for-the-zero** [msgbyte/tailchat#41]
对比discord和kook，功能太少了，语音都没有

**Comment by moonrailgun** [comment]
语音/视频功能正在开发中，目前还有一些交互上细节正在打磨。



> 还有，字体怎么用了衬线字体？

字体方面没有修改过，请问是有什么问题么？对这方面不是很了解

**Comment by for-the-zero** [comment]
我哪里的显示是衬线字体，建议改无衬线字体
css应该能改吧

**Comment by moonrailgun** [comment]
不是很了解这方面的细节。为什么要改呢？
![image](https://user-images.githubusercontent.com/6964737/182143694-94af0658-7225-4c53-ba33-69b8636041ae.png)
我查了下是不是衬线体更加适合长时间阅读？

Reference: https://zhidao.baidu.com/question/143721213389768805.html

**Comment by for-the-zero** [comment]
这些东西不适合用衬线体，那有网站用衬线体，不好看还别扭

随便找的视频
【为什么手机的默认字体是黑体，衬线字体和无衬线体在屏幕上的可读性比较-哔哩哔哩】 https://b23.tv/MEiVPk3

**Comment by moonrailgun** [comment]
@for-the-zero 指定了一下字体样式，麻烦帮忙check一下，我这边没有办法复现你这边的问题（原来默认是走系统字体优先）

**Comment by for-the-zero** [comment]
![image](https://user-images.githubusercontent.com/101497510/182311963-56ae3474-f75f-4a28-9bfc-365fecf1342e.png)

中文不行啊

你这css好像是指定字体，我不是专业的，我觉得应该用浏览器的字体会好些
![image](https://user-images.githubusercontent.com/101497510/182312494-57cca991-267c-44eb-8593-ccc28efc5758.png)

**Comment by moonrailgun** [comment]
> ![image](https://user-images.githubusercontent.com/101497510/182311963-56ae3474-f75f-4a28-9bfc-365fecf1342e.png)
> 
> 中文不行啊
> 
> 你这css好像是指定字体，我不是专业的，我觉得应该用浏览器的字体会好些 ![image](https://user-images.githubusercontent.com/101497510/182312494-57cca991-267c-44eb-8593-ccc28efc5758.png)

我这边是用的github 同款字体。github上的字体在你这边是正常的么？
(BTW 其实我没有看出来你的图上的字体有什么问题)

**Comment by for-the-zero** [comment]
正常，但是调用了浏览器的字体（github的字体没有中文）（Devtools中样式包含font的基本上都花了横线）

**Comment by moonrailgun** [comment]
我看了下百度搜索的字体在我的指定字体范围内。应该是有一致表现的

**Comment by for-the-zero** [comment]
可能有bug，看字体一栏

![image](https://user-images.githubusercontent.com/101497510/182514161-79e62c7a-aec8-4239-ba5c-ebce433bc2b0.png)
![image](https://user-images.githubusercontent.com/101497510/182514203-66608dc2-8572-417f-a6a7-94ac79bec8f7.png)
![image](https://user-images.githubusercontent.com/101497510/182514250-8ab596ef-6a30-4ec3-988f-2e501096a7a9.png)

**Comment by for-the-zero** [comment]
好像没有中文吧

![image](https://user-images.githubusercontent.com/101497510/182514675-d0169332-3061-4eb9-b93d-ed62a898f6ca.png)
![image](https://user-images.githubusercontent.com/101497510/182514877-4f17742d-3486-46b6-8dbb-2c9177d1c81d.png)

要不换成微软雅黑或HarmonyOS Sans SC之类的试试？

**Comment by moonrailgun** [comment]
从知乎那边嫖了一套方案，现在应该是没问题了。

另外可以加入Tailchat Nightly 群组关心 CICD/代码提交 动态
[Tailchat Nightly](https://nightly.paw.msgbyte.com/invite/8Jfm1dWb)

**Comment by for-the-zero** [comment]
还是不行啊
![image](https://user-images.githubusercontent.com/101497510/182515920-35b16e9c-d382-4ade-ab47-ed7012639779.png)
![image](https://user-images.githubusercontent.com/101497510/182516161-443b86b9-9308-4bc3-8397-b708fe2e8fb3.png)
![image](https://user-images.githubusercontent.com/101497510/182516189-2b7efc11-199a-47ce-9ac2-9d7e50afec13.png)

但是输入框可以
![image](https://user-images.githubusercontent.com/101497510/182516324-ded5863a-116b-42de-a304-8b8c78ba39f5.png)
