### ISSUE TITLE
管理面板

### ISSUE THREAD

**Issue by Cloud370** [msgbyte/tailchat#46]
请问管理面板怎么进？看源码是有后台的

**Comment by Cloud370** [comment]
我看到示例的元神社区有全体禁言的功能 但是我自己创建的似乎没找到

**Comment by moonrailgun** [comment]
全体禁言需要等待一段时间。

目前权限组功能(可以设置所有人默认不能发言)正在进行最后的测试和补全。之后会发布tailchat 1.0 正式版。

单个用户的禁言可以直接在成员列表中右键

**Comment by Cloud370** [comment]
好的辛苦了，架构设计得很棒

**Comment by moonrailgun** [comment]
感谢你的支持
