### ISSUE TITLE
可否给个最新视频教程

### ISSUE THREAD

**Issue by hm-Private** [msgbyte/tailchat#52]
急

**Comment by moonrailgun** [comment]
文档是有哪里看不懂么？

**Comment by hm-Private** [comment]
[docker-compose.yml](https://raw.githubusercontent.com/msgbyte/tailchat/master/docker-compose.yml)
[docker-compose.env](https://raw.githubusercontent.com/msgbyte/tailchat/master/docker-compose.env)

修改这两个配置文件,还有https设定,还有我看到又语音视频插件,是否能用

**Comment by hm-Private** [comment]
[root@ser999805290083 ~]# docker pull moonrailgun/tailchat
Using default tag: latest
latest: Pulling from moonrailgun/tailchat
213ec9aee27d: Pull complete 
90d4f1a52341: Pull complete 
96f9ff3b94d8: Pull complete 
f05a94b04b95: Pull complete 
4cc802dd2b7f: Pull complete 
0a08e30987f1: Pull complete 
5f90b627005a: Pull complete 
397bf2538de7: Pull complete 
2d6396dc1c8b: Pull complete 
31f2c8f06ae5: Pull complete 
1418f7300ca7: Pull complete 
3c6c7ce1632a: Pull complete 
ad7a5da41a79: Pull complete 
11f39e16a4c8: Pull complete 
a0d58193ab8c: Pull complete 
67f3406ba73f: Pull complete 
09f0b05c7954: Pull complete 
cb3674eccc53: Pull complete 
855e9e7200a6: Pull complete 
f8e212e1a9ea: Pull complete 
Digest: sha256:87f91c58b4e321e7a91c843d4e713ef717bf521b8999cce1ea049f2285fe88df
Status: Downloaded newer image for moonrailgun/tailchat:latest
docker.io/moonrailgun/tailchat:latest
[root@ser999805290083 ~]# 
搭建到这一步,基本就看不懂了,

docker tag moonrailgun/tailchat tailchat # 修改tag以让配置文件能够识别

这个命令都不知道该怎么修改

**Comment by moonrailgun** [comment]
主要修改的就是 `docker-compose.env` 这个配置文件，默认的话只需要把`API_URL`改为自己的域名即可

https 请自行使用反向代理工具处理

音视频插件还在开发中

**Comment by moonrailgun** [comment]
> [root@ser999805290083 ~]# docker pull moonrailgun/tailchat Using default tag: latest latest: Pulling from moonrailgun/tailchat 213ec9aee27d: Pull complete 90d4f1a52341: Pull complete 96f9ff3b94d8: Pull complete f05a94b04b95: Pull complete 4cc802dd2b7f: Pull complete 0a08e30987f1: Pull complete 5f90b627005a: Pull complete 397bf2538de7: Pull complete 2d6396dc1c8b: Pull complete 31f2c8f06ae5: Pull complete 1418f7300ca7: Pull complete 3c6c7ce1632a: Pull complete ad7a5da41a79: Pull complete 11f39e16a4c8: Pull complete a0d58193ab8c: Pull complete 67f3406ba73f: Pull complete 09f0b05c7954: Pull complete cb3674eccc53: Pull complete 855e9e7200a6: Pull complete f8e212e1a9ea: Pull complete Digest: sha256:87f91c58b4e321e7a91c843d4e713ef717bf521b8999cce1ea049f2285fe88df Status: Downloaded newer image for moonrailgun/tailchat:latest docker.io/moonrailgun/tailchat:latest [root@ser999805290083 ~]# 搭建到这一步,基本就看不懂了,
> 
> docker tag moonrailgun/tailchat tailchat # 修改tag以让配置文件能够识别
> 
> 这个命令都不知道该怎么修改

这个命令不需要修改。。。可能我注释描述有点问题，他的意思是把docker下载的镜像改个名，我改一下注释文案

**Comment by hm-Private** [comment]
docker-compose.env

这个文件怎么修改

Digest: sha256:87f91c58b4e321e7a91c843d4e713ef717bf521b8999cce1ea049f2285fe88df
Status: Downloaded newer image for moonrailgun/tailchat:latest
docker.io/moonrailgun/tailchat:latest
[root@ser999805290083 ~]# docker tag moonrailgun/tailchat tailchat
[root@ser999805290083 ~]# 


执行完就这样

**Comment by moonrailgun** [comment]
辛苦按照教程来一步步处理，可以不需要每走一步都问一下的。

![image](https://user-images.githubusercontent.com/6964737/205437990-52480373-9133-489a-a419-dc2f4901c1e7.png)

**Comment by hm-Private** [comment]
[root@ser999805290083 ~]# cd tailchat
-bash: cd: tailchat: 没有那个文件或目录
[root@ser999805290083 ~]# 
就是找不到这文件

**Comment by moonrailgun** [comment]
cd 到配置文件所在的目录，辛苦看下注释。(如果是源码编译的话默认clone下来是tailchat文件夹)

如果配置放在当前目录的话不需要cd。

**Comment by hm-Private** [comment]
[root@ser999805290083 ~]# ls -a
.  ..  anaconda-ks.cfg  .bash_history  .bash_logout  .bash_profile  .bashrc  .cshrc  .nvm  original-ks.cfg  .pki  Profile  .ssh  .tcshrc
[root@ser999805290083 ~]# tail docker-compose.env
tail: 无法打开"docker-compose.env" 读取数据: 没有那个文件或目录
[root@ser999805290083 ~]# 


好难,找不到,哎

**Comment by moonrailgun** [comment]
基于你的反馈，我调整了一下文档话术。
https://github.com/msgbyte/tailchat/commit/bb2ffdeaac40d55134fe5dfc5025b7e4f6edc681

**Comment by hm-Private** [comment]
直接安装的,,镜像拉取,[docker]我真的 不熟悉,看了以前的教程,发现完全不一样,注释也乱的,根本不是一步一步的安装,跟跳跃一样,我得翻来翻去,大佬给个视频教程吧,或这你帮我安装下吧,我吧机器发你邮箱

**Comment by moonrailgun** [comment]
你需要下载配置文件啊。不然镜像不知道要怎么启动

**Comment by moonrailgun** [comment]
![image](https://user-images.githubusercontent.com/6964737/205438641-59777863-c9c6-416d-bfeb-78dc9583ea96.png)

**Comment by hm-Private** [comment]
我问的,你回复的,都是说一句完事,一点步骤都没有,所以,基本对于我这个小白基本建立不起来

**Comment by hm-Private** [comment]
我问的,你回复的,都是说一句完事,一点步骤都没有,所以,基本对于我这个小白基本建立不起来

**Comment by moonrailgun** [comment]
emmmm.，行吧。

那你需要复制链接，然后下载到服务器上。可以参考如下操作

```bash
mk tailchat && cd tailchat
wget https://raw.githubusercontent.com/msgbyte/tailchat/master/docker-compose.yml
wget https://raw.githubusercontent.com/msgbyte/tailchat/master/docker-compose.env
vim docker-compose.env # 修改环境变量文件中API_URL的值为你自己服务端的外网地址
docker-compose up -d
```

因为我不能预设你下载文件的方式(完全可以手动下载后手动上传)

**Comment by hm-Private** [comment]
大佬,出个视频教程吧,也就20分钟,实在不行我提供机器,8和g你给我一个视频就行.我看着视频一步步操作就简单了,最好吧域名对接https也整上

**Comment by moonrailgun** [comment]
> 大佬,出个视频教程吧,也就20分钟,实在不行我提供机器,8和g你给我一个视频就行.我看着视频一步步操作就简单了,最好吧域名对接https也整上

https 不是强依赖的。(跟tailchat本身没有直接关系)

另外方便说一下到底是哪里看不懂么？就算是视频也是照着文档一步步走的啊。

**Comment by hm-Private** [comment]
就是修改文件看不懂,因为我是镜像拉取,而且我对docker不了解,以我为准的级别,就根本不知道docker装哪去了,所以你之前文档就是让修改文件,我就算下载了,我该上传到哪里去,完全没写,所以之前文档新手根本就看不懂,更别谈搭建了,最好简单一点,步骤清晰到直接建立完成,本省你这也没多少命令,可是就是少中间段落的

**Comment by moonrailgun** [comment]
docker和任何的linux上的软件一样，都是全局安装的(不存在装到那里去的概念，具体在哪里我也很难解释，因为不同的linux发行版是不一样的)

修改文件的话。。。我确实不知道为什么会看不懂，就是改配置。随便是通过各种第三方软件还是vim还是emacs，只要把某个值(已经标出)修改成自己的域名(或者ip)就行了。我自认为已经简化到不能再简化的地步了

至于文件放在那里其实是无所谓的，只要自己能找得到就行。

----------

另外我调整了一下部署文档的结构，现在应该不存在会跳的问题了(之前是需要考虑不同的安装方式，现在区分开了)

**Comment by hm-Private** [comment]
嗯
现在差不多了,但是 还有不详细的,但是我自己解决了,其他人就不知道了

**Comment by hm-Private** [comment]
http://38.34.253.244:11000

能访问了,但是 这个插件怎么用,我看到又语音视频的插件啊

**Comment by moonrailgun** [comment]
如果你觉得有更好的文案或者描述方式，欢迎pr来讨论一下。Tailchat是一个非常开放的应用，欢迎来自所有人的pr

关于插件的使用在插件中心安装即可，有些插件没有写使用文档，但是功能都是全的

音视频插件还在开发中

**Comment by hm-Private** [comment]
我这群邀请别人怎么显示需要注册,我用你的游客是可以直接进入的呀

**Comment by hm-Private** [comment]
http://38.34.253.244:11000/invite/z2FQPcSe

大佬这个怎么才能和你一样,显示立即加入而不是立即注册呢

**Comment by moonrailgun** [comment]
你说的很有道理。因为邀请的话还是期望用户已经登录的，未登录但是期望游客身份接受邀请的确实没有考虑过

> 游客是为了方便用户快速体验，如果接收到他人邀请的话目的是比较明确的了

但是你可以 返回登录->游客登录->创建游客账号 -> 加入群组

**Comment by moonrailgun** [comment]
> http://38.34.253.244:11000/invite/z2FQPcSe
> 
> 大佬这个怎么才能和你一样,显示立即加入而不是立即注册呢

已登录情况下打开就是立即加入

**Comment by hm-Private** [comment]
我中午测试你的是用无痕模式进的,确实能直接进入,不显示立即注册,奇怪了,希望这个问题能尽快解决,更希望整个语音功能,这样游戏开黑是个很好的体验

**Comment by moonrailgun** [comment]
好的感谢你的支持
