### ISSUE TITLE
以后会支持语音聊天功能吗

### ISSUE THREAD

**Issue by f0re1gnKey** [msgbyte/tailchat#53]
就像kook那样的

**Comment by moonrailgun** [comment]
会的，插件已经在开发中了（最迟明年Q1能完成）

https://github.com/msgbyte/tailchat/tree/master/server/plugins/com.msgbyte.meeting

**Comment by ZakiuC** [comment]
大佬，手动怎么部署插件呢

**Comment by moonrailgun** [comment]
> 大佬，手动怎么部署插件呢

前端插件直接通过页面上手动输入json配置即可，后端插件需要手动编译一下镜像，然后在源码的编译配置中手动声明一下就行（目前还比较简陋没有做相关工具），这个声明的目的是为了让后端插件的前端代码被加入到可以安装的阶段，至于后端插件的后端部分只需要放置在 server/plugins 目录下就是被自动加载

https://github.com/msgbyte/tailchat/blob/94fcbb7445e92a0e2ea29c66e0746b18bbd0ed6d/package.json#L14

**Comment by ZakiuC** [comment]
我是用您编译好的镜像部署的，意思是我需要在源码中加入声明和插件再编译部署是吗

**Comment by moonrailgun** [comment]
> 我是用您编译好的镜像部署的，意思是我需要在源码中加入声明和插件再编译部署是吗

你是要搞语音聊天插件是嘛？现在还没有完全ready，等ready后会加入到默认插件列表的

**Comment by ZakiuC** [comment]
> > 我是用您编译好的镜像部署的，意思是我需要在源码中加入声明和插件再编译部署是吗
> 
> 你是要搞语音聊天插件是嘛？现在还没有完全ready，等ready后会加入到默认插件列表的

这样子，了解了

**Comment by moonrailgun** [comment]
> > > 我是用您编译好的镜像部署的，意思是我需要在源码中加入声明和插件再编译部署是吗
> > 
> > 
> > 你是要搞语音聊天插件是嘛？现在还没有完全ready，等ready后会加入到默认插件列表的
> 
> 这样子，了解了

主要是接入的是声网的实现，但是声网太拉了。随便改个配置要花3个工作日审核，大大拖累了开发进程

![image](https://user-images.githubusercontent.com/6964737/210212148-88289786-3c3b-4e0a-bb67-e7f7746954fd.png)

**Comment by moonrailgun** [comment]
已完成

相关文档: https://tailchat.msgbyte.com/zh-Hans/docs/meeting/agora
