### ISSUE TITLE
希望docker版可支持arm

### ISSUE THREAD

**Issue by LeticiaAnna** [msgbyte/tailchat#54]
产品非常给力 希望docker版可支持arm

**Comment by moonrailgun** [comment]
现在是arm环境不能部署么？

**Comment by LeticiaAnna** [comment]
我在docker 版本的 tag 中 发现 tailchat 只支持 amd64

**Comment by moonrailgun** [comment]
tailchat 是全版本支持的(内核无关)

**Comment by zhaoyang90** [comment]
arm无法正常下载，在上传镜像时要指定支持的内核？

**Comment by moonrailgun** [comment]
> arm无法正常下载，在上传镜像时要指定支持的内核？

了解你的点了，我周末会专门处理一下(目前手头没有arm设备)

**Comment by moonrailgun** [comment]
新的版本推送了arm64架构的镜像，我用我的nas设备试验下来没有什么问题。
