### ISSUE TITLE
多久可以适配移动端呢。

### ISSUE THREAD

**Issue by zhetenglife** [msgbyte/tailchat#55]
项目非常棒，终于有国产的开源IM系统啦。。。
在使用场景上，目前只适合PC端工作时来使用。
对移动端多久可以适配呢，另外发送短语音消息也很重要。。。谢谢

**Comment by moonrailgun** [comment]
可以直接通过手机浏览器打开，对于支持pwa的浏览器也可以生成pwa应用。网页端已经做了移动端适配。

短语音消息短时间不会考虑，当然任何人都可以通过开发插件的方式向tailchat提交自己想要的功能（或者不提交自己安装）

**Comment by moonrailgun** [comment]
The beta version of the mobile client has been released, please visit the official website to download
