### ISSUE TITLE
启动找不到dockerfiler？

### ISSUE THREAD

**Issue by HollyMadCow** [msgbyte/tailchat#58]
G:\djt\tc>docker-compose up -d
[+] Running 0/7
 - service-user Warning                                                                                            33.9s  
 - service-group Warning                                                                                           33.9s  
 - service-all-plugins Warning                                                                                     33.8s 
 - service-gateway Warning                                                                                         33.8s  
 - service-file Warning                                                                                             3.4s  
 - service-chat Warning                                                                                            34.4s  
 - service-openapi Warning                                                                                         33.9s
[+] Building 0.1s (2/2) FINISHED
 => [internal] load build definition from Dockerfile                                                                0.1s  
=> => transferring dockerfile: 2B                                                                                  0.0s  
=> [internal] load .dockerignore                                                                                   0.1s  
=> => transferring context: 2B                                                                                     0.0s 
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount1989673091/Dockerfile: no such file or directory

在windows下启动的时候出现这个错误

**Comment by f85386056** [comment]
root@ss1:/home/tailchat# docker compose up -d
[+] Running 3/3
 ! service-all-plugins Warning                                                                                                                                                                                                            2.4s 
 ! service-core Warning                                                                                                                                                                                                                   2.4s 
 ! service-openapi Warning                                                                                                                                                                                                                2.4s 
[+] Building 3.0s (2/2) FINISHED                                                                                                                                                                                                               
 => [service-all-plugins internal] load build definition from Dockerfile                                                                                                                                                                  0.0s
 => => transferring dockerfile: 2B                                                                                                                                                                                                        0.0s
 => [service-all-plugins internal] load .dockerignore                                                                                                                                                                                     0.0s
 => => transferring context: 2B                                                                                                                                                                                                           0.0s
failed to solve: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount3846543571/Dockerfile: no such file or directory
在debian11上使用docker compose 遇到了类似的问题

**Comment by moonrailgun** [comment]
> root@ss1:/home/tailchat# docker compose up -d [+] Running 3/3 ! service-all-plugins Warning 2.4s ! service-core Warning 2.4s ! service-openapi Warning 2.4s [+] Building 3.0s (2/2) FINISHED => [service-all-plugins internal] load build definition from Dockerfile 0.0s => => transferring dockerfile: 2B 0.0s => [service-all-plugins internal] load .dockerignore 0.0s => => transferring context: 2B 0.0s failed to solve: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount3846543571/Dockerfile: no such file or directory 在debian11上使用docker compose 遇到了类似的问题

上面回复的方法不生效么？ @f85386056

**Comment by f85386056** [comment]
> 

是我自己的问题tag没有重新命名
