### ISSUE TITLE
关于插件使用问题

### ISSUE THREAD

**Issue by wzry2580** [msgbyte/tailchat#59]
github，群组订阅这个插件怎么用？，我是按他们上面的步骤搞那个网络钩子，但是好像没有起作用，希望能更新详细使用流程

**Comment by wzry623090** [comment]
还有就是复制功能不好用，因为那个地址无法复制，只能手写真的麻烦

**Comment by moonrailgun** [comment]
按照提示

- 填入github的用户名/仓库名。以本项目为例就是 `msgbyte/tailchat`
- 填入需要发送动态变更是哪个频道

然后在github项目的设置页中配置webhook

你说的不能复制是不能右键打开菜单吧。我不信都会上github了不会有ctrl+c复制。。。

![image](https://user-images.githubusercontent.com/6964737/206841916-578825aa-f1f9-4af3-87b0-9a3d0e920df4.png)

![image](https://user-images.githubusercontent.com/6964737/206841948-05c248d6-ad74-4fbf-b2f6-0509a8d85e5d.png)

----------

你说的404请求是指？

**Comment by moonrailgun** [comment]
因为这个issue已经长时间没有回复了，所以先关了，如果依旧有问题欢迎随时reopen
