### ISSUE TITLE
老哥不考虑建个 q 群么，平时可以聊聊技术方案

### ISSUE THREAD

**Issue by HustCoderHu** [msgbyte/tailchat#60]

**Comment by moonrailgun** [comment]
不玩qq很久了

**Comment by moonrailgun** [comment]
如果有这方面需求的人比较多的话我会开一个群来沟通的，当然如果有条件的话建议可以在tailchat的群组来沟通
https://nightly.paw.msgbyte.com/invite/8Jfm1dWb

**Comment by moonrailgun** [comment]
![mmqrcode1674224795627](https://user-images.githubusercontent.com/6964737/213722810-f205c313-20ad-4efd-a629-b3685d4e7e65.png)

建了个微信群，欢迎加入

**Comment by ZZZ-zero** [comment]
> 

过期了啊

**Comment by moonrailgun** [comment]
> > 
> 
> 过期了啊
> 
> > 
> 
> Expired

见官方网站
