### ISSUE TITLE
更改域名后文件和图片都看不见了。

### ISSUE THREAD

**Issue by lxtnew** [msgbyte/tailchat#72]
发现以前发送的文件和图片链接仍旧是原域名。 怎么样批量修改原内容中的域名指向？

注：
域名修改是通过修改这一行实现的： API_URL=https://tailchat-nightly.moonrailgun.com

**Comment by moonrailgun** [comment]
方式一: 将原来的域名的请求做一个重定向，重定向到新的域名

方式二：修改数据库数据，可以写个mongo的脚本去批量修改。

**Comment by lxtnew** [comment]
能否在数据库中不要存放域名，而是根据 API_URL 动态生成文件和图片的链接 ？

**Comment by moonrailgun** [comment]
> 能否在数据库中不要存放域名，而是根据 API_URL 动态生成文件和图片的链接 ？

主要是考虑到集成第三方对象存储平台的情况，不过你说的问题我有在做解决方案来支持动态的静态服务器路径

**Comment by moonrailgun** [comment]
该问题已修复，更新新镜像即可
