### ISSUE TITLE
cli一键部署从来没成功过......

### ISSUE THREAD

**Issue by OneSoftHaha** [msgbyte/tailchat#75]
Ubuntu，虚拟机，上图
![image](https://user-images.githubusercontent.com/113611411/230395409-86daef41-8825-4e65-a0a5-2d394e68094b.png)
npx tailchat-cli docker update
npx tailchat-cli docker init

**Comment by moonrailgun** [comment]
cli脚本只是拉配置和改配置。并不负责应用的启动
这个问题一般出现在低版本的node环境，但是如果是docker环境的话依赖都会帮你准备好。

方便看一下启动命令么？

**Comment by OneSoftHaha** [comment]
这个就是执行npx tailchat-cli docker update时候会出现的。
这几天全在折腾这个，就是虚拟机里全新的Ubuntu，执行以下命令（没干其他事）
sudo apt update
sudo apt install nodejs npm docker docker-compose
sudo npx tailchat-cli docker update

**Comment by moonrailgun** [comment]
你没有启动命令啊，你这些命令只是在更新内容，类比你只是下载了最新版的软件，但是你想让软件运行起来得双击打开。

这个问题是运行时的node版本过低。

- 如果你用docker 镜像的版本不会出现这个问题，但是你不需要安装node
- 如果你用系统的node不需要更新镜像。但是你需要自己管理依赖，tailchat最低支持的node版本是16.14

**Comment by OneSoftHaha** [comment]
不是没启动，是运行sudo npx tailchat-cli docker update的时候中途就会报错
