### ISSUE TITLE
你有考虑过 solidjs 吗？

### ISSUE THREAD

**Issue by mokeyish** [msgbyte/tailchat#78]
看你用的是 react，个人是比较喜欢 react 的 jsx 风格代码，灵活。但是 react 的性能有点，solidjs 刚好补足了这个性能上的缺点，并且也不需要 react hook 那么繁杂的设计。

这里有对比文章：https://ogzhanolguncu.com/blog/react-vs-solid
还有 benchmark: [https://krausest.github.io/js-framework-benchmark](https://krausest.github.io/js-framework-benchmark/current.html#eyJmcmFtZXdvcmtzIjpbImtleWVkL2FscGluZSIsImtleWVkL2FuZ3VsYXIiLCJrZXllZC9saXQiLCJrZXllZC9wcmVhY3QiLCJrZXllZC9yZWFjdCIsImtleWVkL3NvbGlkIiwia2V5ZWQvc3ZlbHRlIiwia2V5ZWQvdmFuaWxsYWpzIiwia2V5ZWQvdnVlIiwia2V5ZWQveWV3Iiwibm9uLWtleWVkL2FwcHJ1biIsIm5vbi1rZXllZC9hcnQiLCJub24ta2V5ZWQvYXVyZWxpYSIsIm5vbi1rZXllZC9iZGMiLCJub24ta2V5ZWQvYmluZGluZy5zY2FsYSIsIm5vbi1rZXllZC9jYWxsYmFnLWpzeCIsIm5vbi1rZXllZC9jYWxsYmFnLWpzeC1saXN0Iiwibm9uLWtleWVkL2NydWkiLCJub24ta2V5ZWQvY3ljbGVqcy1kb20iLCJub24ta2V5ZWQvZGF0dW0iLCJub24ta2V5ZWQvZGVsb3JlYW4iLCJub24ta2V5ZWQvZG9qbyIsIm5vbi1rZXllZC9kb21kaWZmIiwibm9uLWtleWVkL2RvbXZtIiwibm9uLWtleWVkL2Rvb2h0bWwiLCJub24ta2V5ZWQvZG96Iiwibm9uLWtleWVkL2VmLWpzIiwibm9uLWtleWVkL2VsbSIsIm5vbi1rZXllZC9lbmRvcnBoaW4iLCJub24ta2V5ZWQvZXRjaCIsIm5vbi1rZXllZC9maWRhbiIsIm5vbi1rZXllZC9mcmUiLCJub24ta2V5ZWQvaGFsb2dlbiIsIm5vbi1rZXllZC9oZXJlc3kiLCJub24ta2V5ZWQvaHVsbG8iLCJub24ta2V5ZWQvaHlkcm8tanMiLCJub24ta2V5ZWQvaW1iYSIsIm5vbi1rZXllZC9pbmZlcm5vIiwibm9uLWtleWVkL2xpZ2h0ZXJodG1sIiwibm9uLWtleWVkL2xpdCIsIm5vbi1rZXllZC9saXQtaHRtbCIsIm5vbi1rZXllZC9saXRlcmFsanMiLCJub24ta2V5ZWQvbWFxdWV0dGUiLCJub24ta2V5ZWQvbWlrYWRvIiwibm9uLWtleWVkL21pbWJsIiwibm9uLWtleWVkL21pc28iLCJub24ta2V5ZWQvbW9vbiIsIm5vbi1rZXllZC9uZW93Iiwibm9uLWtleWVkL25ldmVybGFuZCIsIm5vbi1rZXllZC9wb2x5bWVyIiwibm9uLWtleWVkL3JhY3RpdmUiLCJub24ta2V5ZWQvcmVhY3QiLCJub24ta2V5ZWQvcmVkb20iLCJub24ta2V5ZWQvcmVmbGV4LWRvbSIsIm5vbi1rZXllZC9yaW90Iiwibm9uLWtleWVkL3NhbiIsIm5vbi1rZXllZC9zYXVyb24iLCJub24ta2V5ZWQvc2NhcmxldHMtZnJhbWUiLCJub24ta2V5ZWQvc2VlZCIsIm5vbi1rZXllZC9zaWZyciIsIm5vbi1rZXllZC9zaW1pIiwibm9uLWtleWVkL3NsaW0tanMiLCJub24ta2V5ZWQvc2xpbmdqcyIsIm5vbi1rZXllZC9zdGR3ZWIiLCJub24ta2V5ZWQvc3RlbSIsIm5vbi1rZXllZC9zdmVsdGUiLCJub24ta2V5ZWQvdWh0bWwiLCJub24ta2V5ZWQvdWk1LXdlYmNvbXBvbmVudHMiLCJub24ta2V5ZWQvdmFuaWxsYS1kb20tZnJhbWV3b3JrIiwibm9uLWtleWVkL3ZhbmlsbGFqcyIsIm5vbi1rZXllZC92YW5pbGxhanMtMSIsIm5vbi1rZXllZC92dWUiXSwiYmVuY2htYXJrcyI6WyIwMV9ydW4xayIsIjAyX3JlcGxhY2UxayIsIjAzX3VwZGF0ZTEwdGgxa194MTYiLCIwNF9zZWxlY3QxayIsIjA1X3N3YXAxayIsIjA2X3JlbW92ZS1vbmUtMWsiLCIwN19jcmVhdGUxMGsiLCIwOF9jcmVhdGUxay1hZnRlcjFrX3gyIiwiMDlfY2xlYXIxa194OCIsIjIxX3JlYWR5LW1lbW9yeSIsIjIyX3J1bi1tZW1vcnkiLCIyM191cGRhdGU1LW1lbW9yeSIsIjI1X3J1bi1jbGVhci1tZW1vcnkiLCIyNl9ydW4tMTBrLW1lbW9yeSIsIjMxX3N0YXJ0dXAtY2kiLCIzNF9zdGFydHVwLXRvdGFsYnl0ZXMiXSwiZGlzcGxheU1vZGUiOjEsImNhdGVnb3JpZXMiOlsxLDIsMyw0LDVdfQ==)

**Comment by moonrailgun** [comment]
1. react 的生态远远超过solidjs, 目前solidjs的生态还无法支持一个企业级项目的快速迭代(之所以说快速迭代是因为如果想把react现有的轮子再造一遍是可行的)
2. solidjs的使用者远远少于vue/react。这对开源项目寻求协作者是非常不利的
3.在实际应用开发中远远无法触及所谓的性能瓶颈，大多数的性能问题都可以以设计来规避。
4. 我也很喜欢solid，但是一个项目的技术选型往往不是因为某个框架酷、性能好、设计优秀来决定的。譬如js总所周知是一门辣鸡语言，但是全球的js使用者是最多的。

-----

另外你贴的博客中性能比较是不公平的，如果要比较小应用的运行效率问题，应该和svelte进行比较，因为两者做了类似的设计

**Comment by mokeyish** [comment]
solidjs 确实组件库很少，要用也是结合 tailwind 和 unocss 这样的 css 组件库。先前也用过 svelte，虽然写起来简洁，但它的数据更新有坑，必须显示等号赋值才能被编译器识别到这是需要响应式的。而且 sfc 模式，虽然理念挺好，但是对于一个组件，内部可复用的小组件，一两行代码可搞定，也要另外建个文件就麻烦了。


另外，你这个项目界面不错👍，是 discord 风格。先前想，都 2023 年了，手机网络已经全面普及 ipv6，如何结合 p2p 库 https://github.com/libp2p/rust-libp2p

完全可以做一个完全 p2p 聊天，没有第三方监控，100% 保护隐私的聊天工具。

本想折腾一下的，继续 rust-libp2p 写个聊天后端，再找个合适的前端界面，不过实在精力有限，最近在移植 smartdns 到 rust 的 smartdns-rs 版，让 dns 查询可以加密，保护隐私，避免明文 dns 查询被网络其他中间者抓取。


后面有时间还是要折腾下 p2p 聊天工具的。先 star 你的项目😁

**Comment by moonrailgun** [comment]
其实可以作为一个tailchat的p2p聊天插件。tailchat已经提供了大部分通用的功能，只需要专注于逻辑即可

**Comment by Mrcxt** [comment]
jsx+proxy，是我的梦中框架了。没有烦人的.value，没有操心的useEffect闭包，爱了爱了， 可惜没有好用的组件库啊
