### ISSUE TITLE
需要手动部署方案

### ISSUE THREAD

**Issue by Micraow** [msgbyte/tailchat#85]
我的服务器不支持Docker,我想知道能不能给出手动部署的指南？谢谢！

**Comment by moonrailgun** [comment]
好的，我会在这两天内增加手动部署的指南

**Comment by moonrailgun** [comment]
增加了手动部署的相关文档。

https://tailchat.msgbyte.com/zh-Hans/docs/deployment/manual

辛苦看一下，如果有问题/没看懂的欢迎随时沟通，帮助我们改进文档。（在你真正手动部署成功前我先不关这个issue了）

**Comment by moonrailgun** [comment]
是的。特别是前端代码，编译所需要的资源会比较多(4到8g的内存会比较合适).
你可以，特别是前端代码，放在本地去编译，后端编译所需要的资源没有这么高。

**Comment by Micraow** [comment]
现在有个小问题，我的服务器上已经有了其他服务，443，80，端口被占用，我该如何正确配置nginx并使用我自己的证书？有什么要特别注意的吗？

**Comment by moonrailgun** [comment]
你可以使用反向代理工具将来自不同的流量转发到对应的服务上。
关于这点我觉得问baidu会比较快。
