### ISSUE TITLE
1panel面板部署

### ISSUE THREAD

**Issue by Zuo-qing** [msgbyte/tailchat#86]

**Comment by moonrailgun** [comment]
Please describe your problem in detail

**Comment by Zuo-qing** [comment]
1panel Is there a tutorial for deploying the server panel?

moonrailgun ***@***.***>于2023年6月14日 周三15:17写道：

**Comment by Zuo-qing** [comment]
My server control panel is 1panel.

Qing Zuo ***@***.***>于2023年6月14日 周三15:29写道：

**Comment by moonrailgun** [comment]
Just install from appstore is ok.

if you can install other apps, then you can install tailchat.

**Comment by Zuo-qing** [comment]
Ok, thanks.
It can be deployed with one click, right?

moonrailgun ***@***.***>于2023年6月14日 周三15:43写道：

**Comment by moonrailgun** [comment]
yep, its why i try to put it on 1panel appstore.

you just should prepare dependency like mongo... and complete setup form, then you can see your tailchat in your server(not include admin platform, we will add it in later. maybe its a independent service, we will talk over with 1panel developer)

**Comment by Zuo-qing** [comment]
Oh, oh, oh That is to say, I need to install the management platform by
myself, right?

moonrailgun ***@***.***>于2023年6月14日 周三15:57写道：

**Comment by moonrailgun** [comment]
Its optional. you dont need it in most case

**Comment by Zuo-qing** [comment]
Got it. Thank you very much. 😁

moonrailgun ***@***.***>于2023年6月14日 周三16:04写道：
