### ISSUE TITLE
文件大小参数FILE_LIMIT

### ISSUE THREAD

**Issue by Hardwell99** [msgbyte/tailchat#87]
docker compose方式安装，
按照文档在 **docker-compose.env** 配置了 **FILE_LIMIT**  参数
`# file
API_URL=192.168.10.36
FILE_LIMIT=314572800`

重新启动了似乎不起作用，依然显示
`上传失败, 支持的文件最大大小为: 1 MiB`

**Comment by Hardwell99** [comment]
fine
再仔细阅读文档后，我尝试清除docker缓存后重新启动
`docker system prune

docker compose up -d`
可以将该配置生效

**Comment by Hardwell99** [comment]
solved

**Comment by moonrailgun** [comment]
为了确保服务质量，配置相关内容修改后需要清理服务端缓存，否则无法立即生效。

你可以选择以下方式清理缓存: 
- 把redis服务删除重建
- 在admin-next中点击清理所有缓存按钮
- 手动进入redis服务，找到标记为config client 关键字的key，删除即可
