### ISSUE TITLE
安卓端无限转圈圈

### ISSUE THREAD

**Issue by OneSoftHaha** [msgbyte/tailchat#89]
安卓端无限转圈圈
网页却正常打开
还tm是内网加载
![QQ图片20230618091941](https://github.com/msgbyte/tailchat/assets/113611411/000b50eb-4f92-4bda-b13f-d2317da3f819)
![QQ图片20230618091954](https://github.com/msgbyte/tailchat/assets/113611411/d8ed318f-6c6b-4922-ad8c-342c527bf404)

**Comment by OneSoftHaha** [comment]
![涂鸦_Screenshot_2023-06-18-09-22-06-708_Tailchat](https://github.com/msgbyte/tailchat/assets/113611411/6e8fdacf-4e1e-4da3-ab39-630da9135c65)
主界面已经识别版本号了，但是点进去就转圈圈
你的演示站也一样，都进不去

**Comment by moonrailgun** [comment]
信息有点少。你用的是什么软件？看上去是环境的问题。

**Comment by OneSoftHaha** [comment]
就是官网下的客户端

**Comment by OneSoftHaha** [comment]
加载了10多分钟，还是继续转，基本排除第一次久后面快了

**Comment by moonrailgun** [comment]
我的意思是你的截图看上去是用了一个第三方软件/沙盒来运行应用。有没有试过直接运行呢？

因为这是最基本的静态资源网络请求，我本来有一个猜想是因为你使用的是http协议系统自动中断了不安全的网络协议，但是看你说你连接nightly服务也有问题，那我就不了解了。

**Comment by moonrailgun** [comment]
直接打开可以么？我没有坚果手机没有办法测试。

**Comment by OneSoftHaha** [comment]
就是直接打开，相当于直接打开后分屏而已没啥其它功能，很分屏一样的

**Comment by OneSoftHaha** [comment]
录了个视频，第一个打开的是网页版，第二个打开的是app，后面也演示了一步

**Comment by moonrailgun** [comment]
因为你这边的问题就是静态资源加载问题，跟代码没有任何关系。

就好像你用浏览器下载一个文件一直不成功，但是换个浏览器就好了。那么问题当然要找是不是运行环境的问题。

**Comment by OneSoftHaha** [comment]
录屏给看一下，第一个开的是网页版，第二个开的app

https://github.com/msgbyte/tailchat/assets/113611411/88b46398-3fd6-4856-9f70-9f4343bb616c

**Comment by OneSoftHaha** [comment]
对了还有，为啥开app的时候好像会自动跳转到天气一下啊(细看打开app后白了一下然后就会在顶栏显示天气并且每次都会这样)

**Comment by moonrailgun** [comment]
这就不清楚了。实际上app就是内置一个浏览器并在浏览器打开来自不同服务器的资源。同时增加一些移动端的支持(目前是支持手机推送，后续会增加二维码、手机定位等浏览器不支持但是手机原生支持的能力)

**Comment by moonrailgun** [comment]
你可以理解为在微信打开小程序是差不多的感觉

**Comment by OneSoftHaha** [comment]
真tm奇怪，进VMOS里面安装一开就能用了

**Comment by moonrailgun** [comment]
话说我没看到你说的弹天气啊。

**Comment by moonrailgun** [comment]
话说我没看到你说的弹天气啊。

**Comment by OneSoftHaha** [comment]
仔细看视频，我开app的时候加载时突然弹了个白色窗口，然后通知栏就显示了天气

**Comment by Thexiaoyuqaq** [comment]
尝试通过反向代理的方式加上ssl 使用https方式连接

**Comment by Thexiaoyuqaq** [comment]
小雨已收到你的来信已存放至小雨的收件箱
