### ISSUE TITLE
无法启动mysql  重新编译报错  环境centos docker

### ISSUE THREAD

**Issue by Tacit-git** [msgbyte/tailchat#91]
[+] Building 0.5s (6/6) FINISHED                                                                                                                                          
 => [service-user internal] load build definition from Dockerfile                                                                                                    0.0s
 => => transferring dockerfile: 2B                                                                                                                                   0.0s
 => [service-user internal] load .dockerignore                                                                                                                       0.0s
 => => transferring context: 2B                                                                                                                                      0.0s
 => [service-chat internal] load .dockerignore                                                                                                                       0.1s
 => => transferring context: 2B                                                                                                                                      0.0s
 => [service-chat internal] load build definition from Dockerfile                                                                                                    0.0s
 => => transferring dockerfile: 2B                                                                                                                                   0.0s
 => [service-group internal] load build definition from Dockerfile                                                                                                   0.0s
 => => transferring dockerfile: 2B                                                                                                                                   0.0s
 => [service-group internal] load .dockerignore                                                                                                                      0.0s
 => => transferring context: 2B                                                                                                                                      0.0s
failed to solve: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount1653574029/Dockerfile: no such file or directory

报错，求帮助

**Comment by moonrailgun** [comment]
首先tailchat没有包含mysql。。
然后如果对docker了解不深，可以使用官方镜像按照教程来操作。一共也没有几步
https://tailchat.msgbyte.com/docs/deployment/docker-compose

**Comment by moonrailgun** [comment]
因为这个issue已经很长时间没有回复了，我先把这个issue close了，如果有需要可以随时reopen
