### ISSUE TITLE
admin后台无法创建，查看用户 || admin background cannot be created, view users

### ISSUE THREAD

**Issue by Peterzhangnoise** [msgbyte/tailchat#98]
上层nginx反代，加ssl实现https
![image](https://github.com/msgbyte/tailchat/assets/70377914/740bd4c8-9a16-4541-86b4-2c626a86d041)

---
The upper layer nginx reverse generation, add ssl to achieve https
![image](https://github.com/msgbyte/tailchat/assets/70377914/740bd4c8-9a16-4541-86b4-2c626a86d041)

**Comment by moonrailgun** [comment]
这是因为你的jwt没有通过验证导致的，可能是因为上一次签发的token和最新的秘钥无法匹配上导致的，理论上应该会回到登录页面才对啊？退出登录后重进后台看看呢？

**Comment by Peterzhangnoise** [comment]
> 这是因为你的jwt没有通过验证导致的，可能是因为上一次签发的token和最新的秘钥无法匹配上导致的，理论上应该会回到登录页面才对啊？退出登录后重进后台看看呢？
> 
> This is because your jwt has not passed the verification. It may be because the token issued last time does not match the latest secret key. In theory, it should return to the login page, right? How about logging out and re-entering the background?

退出登录还是一样，我甚至还清楚浏览器缓存试了下

**Comment by Peterzhangnoise** [comment]
还发现一个问题浏览器在登陆页面的时候登陆第一下是不会跳转的，这时候拿到一个token,再点下登陆才会跳转，然后又拿到一个新的token，如果expiredAt是时间戳的话，那么这个时间在两个小时后

**Comment by moonrailgun** [comment]
感谢反馈，确实是有些问题。将会在今天发布1.8.2版本修复该问题

**Comment by moonrailgun** [comment]
v1.8.2 has been released
